
############  input_number:  #####################  
input_number:
  back_door_accesscount_6:
    name: Access Count
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Openings Left"

#################  input_datetime:  ##############  
input_datetime:
  back_end_date_6:
    name: 'End'
    has_time: false
    has_date: true
  back_start_date_6:
    name: 'Start'
    has_time: false
    has_date: true


  back_sun_start_date_6:
    name: 'Start'
    has_time: true
    has_date: false
  back_sun_end_date_6:
    name: 'End'
    has_time: true
    has_date: false

  back_mon_start_date_6:
    name: 'Start'
    has_time: true
    has_date: false
  back_mon_end_date_6:
    name: 'End'
    has_time: true
    has_date: false

  back_tue_start_date_6:
    name: 'Start'
    has_time: true
    has_date: false
  back_tue_end_date_6:
    name: 'End'
    has_time: true
    has_date: false

  back_wed_start_date_6:
    name: 'Start'
    has_time: true
    has_date: false
  back_wed_end_date_6:
    name: 'End'
    has_time: true
    has_date: false

  back_thu_start_date_6:
    name: 'Start'
    has_time: true
    has_date: false
  back_thu_end_date_6:
    name: 'End'
    has_time: true
    has_date: false

  back_fri_start_date_6:
    name: 'Start'
    has_time: true
    has_date: false
  back_fri_end_date_6:
    name: 'End'
    has_time: true
    has_date: false

  back_sat_start_date_6:
    name: 'Start'
    has_time: true
    has_date: false
  back_sat_end_date_6:
    name: 'End'
    has_time: true
    has_date: false


####################  input_text:  ###############  
input_text:
  back_door_name_6:
    name: 'Name'
  back_door_pin_6:
    name: 'PIN'

#################  input_boolean: ################  
input_boolean:
  back_door_notify_6:
    name: 'Notifications'
  back_door_daterange_6:
    name: 'Use Date Range'
  back_door_smtwtfs_6:
    name: 'Use SMTWTFS'
  back_door_enabled_6:
    name: 'Enabled'
  back_door_accesslimit_6:
    name: 'Limit Access Count'
    initial: off

  back_sun_6:
    name: 'Sunday'
    initial: on

  back_mon_6:
    name: 'Monday'
    initial: on

  back_tue_6:
    name: 'Tuesday'
    initial: on

  back_wed_6:
    name: 'Wednesday'
    initial: on

  back_thu_6:
    name: 'Thursday'
    initial: on

  back_fri_6:
    name: 'Friday'
    initial: on

  back_sat_6:
    name: 'Saturday'
    initial: on

################  binary_sensor: #################  
binary_sensor:

- platform: template
  sensors:

    back_door_enabled_6:
      value_template: "{{ is_state('input_boolean.back_door_enabled_6', 'on') }}"

    back_door_daterange_6:
      value_template: "{{ ((is_state('input_boolean.back_door_daterange_6', 'off') or (states.input_datetime.start_date_6.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string <= now().strftime('%Y%m%d')) and (states.input_datetime.end_date_6.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string >=  now().strftime('%Y%m%d'))}}"

    back_sun_6:
      value_template: "{{ ((is_state('input_boolean.back_sun_6', 'on'))) and (now().strftime('%A') == 'Sunday') and ((states.input_datetime.back_sun_start_date_6.state  == states.input_datetime.back_sun_end_date_6.state) or ((states.input_datetime.back_sun_start_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_sun_end_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_mon_6:
      value_template: "{{ ((is_state('input_boolean.back_mon_6', 'on'))) and (now().strftime('%A') == 'Monday') and ((states.input_datetime.back_mon_start_date_6.state  == states.input_datetime.back_mon_end_date_6.state) or ((states.input_datetime.back_mon_start_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_mon_end_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_tue_6:
      value_template: "{{ ((is_state('input_boolean.back_tue_6', 'on'))) and (now().strftime('%A') == 'Tuesday') and ((states.input_datetime.back_tue_start_date_6.state  == states.input_datetime.back_tue_end_date_6.state) or ((states.input_datetime.back_tue_start_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_tue_end_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_wed_6:
      value_template: "{{ ((is_state('input_boolean.back_wed_6', 'on'))) and (now().strftime('%A') == 'Wednesday') and ((states.input_datetime.back_wed_start_date_6.state  == states.input_datetime.back_wed_end_date_6.state) or ((states.input_datetime.back_wed_start_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_wed_end_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_thu_6:
      value_template: "{{ ((is_state('input_boolean.back_thu_6', 'on'))) and (now().strftime('%A') == 'Thursday') and ((states.input_datetime.back_thu_start_date_6.state  == states.input_datetime.back_thu_end_date_6.state) or ((states.input_datetime.back_thu_start_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_thu_end_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_fri_6:
      value_template: "{{ ((is_state('input_boolean.back_fri_6', 'on'))) and (now().strftime('%A') == 'Friday') and ((states.input_datetime.back_fri_start_date_6.state  == states.input_datetime.back_fri_end_date_6.state) or ((states.input_datetime.back_fri_start_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_fri_end_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_sat_6:
      value_template: "{{ ((is_state('input_boolean.back_sat_6', 'on'))) and (now().strftime('%A') == 'Saturday') and ((states.input_datetime.back_sat_start_date_6.state  == states.input_datetime.back_sat_end_date_6.state) or ((states.input_datetime.back_sat_start_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_sat_end_date_6.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"


    back_smtwtfs_6:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.back_sun_6', 'on')  or  
            is_state('binary_sensor.back_mon_6', 'on')  or  
            is_state('binary_sensor.back_tue_6', 'on')  or  
            is_state('binary_sensor.back_wed_6', 'on')  or  
            is_state('binary_sensor.back_thu_6', 'on')  or  
            is_state('binary_sensor.back_fri_6', 'on')  or  
            is_state('binary_sensor.back_sat_6', 'on')   
         }}

    
    back_access_count_6:
      friendly_name: "Access Count"
      value_template: >-
         {{
            (is_state('input_boolean.back_door_accesslimit_6', 'off'))  or  
            (states.input_number.back_door_accesscount_6.state | int > 0)
         }}


    back_door_active_6:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.back_door_enabled_6', 'on')  and  
            is_state('binary_sensor.back_access_count_6', 'on')  and  
            is_state('binary_sensor.back_door_daterange_6', 'on') and
            is_state('binary_sensor.back_smtwtfs_6', 'on')  
         }}
      device_class: connectivity