
############  input_number:  #####################  
input_number:
  back_door_accesscount_2:
    name: Access Count
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Openings Left"

#################  input_datetime:  ##############  
input_datetime:
  back_end_date_2:
    name: 'End'
    has_time: false
    has_date: true
  back_start_date_2:
    name: 'Start'
    has_time: false
    has_date: true


  back_sun_start_date_2:
    name: 'Start'
    has_time: true
    has_date: false
  back_sun_end_date_2:
    name: 'End'
    has_time: true
    has_date: false

  back_mon_start_date_2:
    name: 'Start'
    has_time: true
    has_date: false
  back_mon_end_date_2:
    name: 'End'
    has_time: true
    has_date: false

  back_tue_start_date_2:
    name: 'Start'
    has_time: true
    has_date: false
  back_tue_end_date_2:
    name: 'End'
    has_time: true
    has_date: false

  back_wed_start_date_2:
    name: 'Start'
    has_time: true
    has_date: false
  back_wed_end_date_2:
    name: 'End'
    has_time: true
    has_date: false

  back_thu_start_date_2:
    name: 'Start'
    has_time: true
    has_date: false
  back_thu_end_date_2:
    name: 'End'
    has_time: true
    has_date: false

  back_fri_start_date_2:
    name: 'Start'
    has_time: true
    has_date: false
  back_fri_end_date_2:
    name: 'End'
    has_time: true
    has_date: false

  back_sat_start_date_2:
    name: 'Start'
    has_time: true
    has_date: false
  back_sat_end_date_2:
    name: 'End'
    has_time: true
    has_date: false


####################  input_text:  ###############  
input_text:
  back_door_name_2:
    name: 'Name'
  back_door_pin_2:
    name: 'PIN'

#################  input_boolean: ################  
input_boolean:
  back_door_notify_2:
    name: 'Notifications'
  back_door_daterange_2:
    name: 'Use Date Range'
  back_door_smtwtfs_2:
    name: 'Use SMTWTFS'
  back_door_enabled_2:
    name: 'Enabled'
  back_door_accesslimit_2:
    name: 'Limit Access Count'
    initial: off

  back_sun_2:
    name: 'Sunday'
    initial: on

  back_mon_2:
    name: 'Monday'
    initial: on

  back_tue_2:
    name: 'Tuesday'
    initial: on

  back_wed_2:
    name: 'Wednesday'
    initial: on

  back_thu_2:
    name: 'Thursday'
    initial: on

  back_fri_2:
    name: 'Friday'
    initial: on

  back_sat_2:
    name: 'Saturday'
    initial: on

################  binary_sensor: #################  
binary_sensor:

- platform: template
  sensors:

    back_door_enabled_2:
      value_template: "{{ is_state('input_boolean.back_door_enabled_2', 'on') }}"

    back_door_daterange_2:
      value_template: "{{ ((is_state('input_boolean.back_door_daterange_2', 'off') or (states.input_datetime.start_date_2.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string <= now().strftime('%Y%m%d')) and (states.input_datetime.end_date_2.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string >=  now().strftime('%Y%m%d'))}}"

    back_sun_2:
      value_template: "{{ ((is_state('input_boolean.back_sun_2', 'on'))) and (now().strftime('%A') == 'Sunday') and ((states.input_datetime.back_sun_start_date_2.state  == states.input_datetime.back_sun_end_date_2.state) or ((states.input_datetime.back_sun_start_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_sun_end_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_mon_2:
      value_template: "{{ ((is_state('input_boolean.back_mon_2', 'on'))) and (now().strftime('%A') == 'Monday') and ((states.input_datetime.back_mon_start_date_2.state  == states.input_datetime.back_mon_end_date_2.state) or ((states.input_datetime.back_mon_start_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_mon_end_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_tue_2:
      value_template: "{{ ((is_state('input_boolean.back_tue_2', 'on'))) and (now().strftime('%A') == 'Tuesday') and ((states.input_datetime.back_tue_start_date_2.state  == states.input_datetime.back_tue_end_date_2.state) or ((states.input_datetime.back_tue_start_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_tue_end_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_wed_2:
      value_template: "{{ ((is_state('input_boolean.back_wed_2', 'on'))) and (now().strftime('%A') == 'Wednesday') and ((states.input_datetime.back_wed_start_date_2.state  == states.input_datetime.back_wed_end_date_2.state) or ((states.input_datetime.back_wed_start_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_wed_end_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_thu_2:
      value_template: "{{ ((is_state('input_boolean.back_thu_2', 'on'))) and (now().strftime('%A') == 'Thursday') and ((states.input_datetime.back_thu_start_date_2.state  == states.input_datetime.back_thu_end_date_2.state) or ((states.input_datetime.back_thu_start_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_thu_end_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_fri_2:
      value_template: "{{ ((is_state('input_boolean.back_fri_2', 'on'))) and (now().strftime('%A') == 'Friday') and ((states.input_datetime.back_fri_start_date_2.state  == states.input_datetime.back_fri_end_date_2.state) or ((states.input_datetime.back_fri_start_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_fri_end_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    back_sat_2:
      value_template: "{{ ((is_state('input_boolean.back_sat_2', 'on'))) and (now().strftime('%A') == 'Saturday') and ((states.input_datetime.back_sat_start_date_2.state  == states.input_datetime.back_sat_end_date_2.state) or ((states.input_datetime.back_sat_start_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.back_sat_end_date_2.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"


    back_smtwtfs_2:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.back_sun_2', 'on')  or  
            is_state('binary_sensor.back_mon_2', 'on')  or  
            is_state('binary_sensor.back_tue_2', 'on')  or  
            is_state('binary_sensor.back_wed_2', 'on')  or  
            is_state('binary_sensor.back_thu_2', 'on')  or  
            is_state('binary_sensor.back_fri_2', 'on')  or  
            is_state('binary_sensor.back_sat_2', 'on')   
         }}

    
    back_access_count_2:
      friendly_name: "Access Count"
      value_template: >-
         {{
            (is_state('input_boolean.back_door_accesslimit_2', 'off'))  or  
            (states.input_number.back_door_accesscount_2.state | int > 0)
         }}


    back_door_active_2:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.back_door_enabled_2', 'on')  and  
            is_state('binary_sensor.back_access_count_2', 'on')  and  
            is_state('binary_sensor.back_door_daterange_2', 'on') and
            is_state('binary_sensor.back_smtwtfs_2', 'on')  
         }}
      device_class: connectivity