
############  input_number:  #####################  
input_number:
  front_door_accesscount_4:
    name: Access Count
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Openings Left"

#################  input_datetime:  ##############  
input_datetime:
  front_end_date_4:
    name: 'End'
    has_time: false
    has_date: true
  front_start_date_4:
    name: 'Start'
    has_time: false
    has_date: true


  front_sun_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  front_sun_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  front_mon_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  front_mon_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  front_tue_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  front_tue_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  front_wed_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  front_wed_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  front_thu_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  front_thu_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  front_fri_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  front_fri_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  front_sat_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  front_sat_end_date_4:
    name: 'End'
    has_time: true
    has_date: false


####################  input_text:  ###############  
input_text:
  front_door_name_4:
    name: 'Name'
  front_door_pin_4:
    name: 'PIN'

#################  input_boolean: ################  
input_boolean:
  front_door_notify_4:
    name: 'Notifications'
  front_door_daterange_4:
    name: 'Use Date Range'
  front_door_front_smtwtfs_4:
    name: 'Use SMTWTFS'
  front_door_enabled_4:
    name: 'Enabled'
  front_door_accesslimit_4:
    name: 'Limit Access Count'
    initial: off

  front_sun_4:
    name: 'Sunday'
    initial: on

  front_mon_4:
    name: 'Monday'
    initial: on

  front_tue_4:
    name: 'Tuesday'
    initial: on

  front_wed_4:
    name: 'Wednesday'
    initial: on

  front_thu_4:
    name: 'Thursday'
    initial: on

  front_fri_4:
    name: 'Friday'
    initial: on

  front_sat_4:
    name: 'Saturday'
    initial: on

################  binary_sensor: #################  
binary_sensor:

- platform: template
  sensors:

    front_door_enabled_4:
      value_template: "{{ is_state('input_boolean.front_door_enabled_4', 'on') }}"

    front_door_daterange_4:
      value_template: "{{ ((is_state('input_boolean.front_door_daterange_4', 'off') or (states.input_datetime.start_date_4.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string <= now().strftime('%Y%m%d')) and (states.input_datetime.end_date_4.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string >=  now().strftime('%Y%m%d'))}}"

    front_sun_4:
      value_template: "{{ ((is_state('input_boolean.front_sun_4', 'on'))) and (now().strftime('%A') == 'Sunday') and ((states.input_datetime.front_sun_start_date_4.state  == states.input_datetime.front_sun_end_date_4.state) or ((states.input_datetime.front_sun_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.front_sun_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    front_mon_4:
      value_template: "{{ ((is_state('input_boolean.front_mon_4', 'on'))) and (now().strftime('%A') == 'Monday') and ((states.input_datetime.front_mon_start_date_4.state  == states.input_datetime.front_mon_end_date_4.state) or ((states.input_datetime.front_mon_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.front_mon_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    front_tue_4:
      value_template: "{{ ((is_state('input_boolean.front_tue_4', 'on'))) and (now().strftime('%A') == 'Tuesday') and ((states.input_datetime.front_tue_start_date_4.state  == states.input_datetime.front_tue_end_date_4.state) or ((states.input_datetime.front_tue_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.front_tue_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    front_wed_4:
      value_template: "{{ ((is_state('input_boolean.front_wed_4', 'on'))) and (now().strftime('%A') == 'Wednesday') and ((states.input_datetime.front_wed_start_date_4.state  == states.input_datetime.front_wed_end_date_4.state) or ((states.input_datetime.front_wed_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.front_wed_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    front_thu_4:
      value_template: "{{ ((is_state('input_boolean.front_thu_4', 'on'))) and (now().strftime('%A') == 'Thursday') and ((states.input_datetime.front_thu_start_date_4.state  == states.input_datetime.front_thu_end_date_4.state) or ((states.input_datetime.front_thu_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.front_thu_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    front_fri_4:
      value_template: "{{ ((is_state('input_boolean.front_fri_4', 'on'))) and (now().strftime('%A') == 'Friday') and ((states.input_datetime.front_fri_start_date_4.state  == states.input_datetime.front_fri_end_date_4.state) or ((states.input_datetime.front_fri_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.front_fri_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    front_sat_4:
      value_template: "{{ ((is_state('input_boolean.front_sat_4', 'on'))) and (now().strftime('%A') == 'Saturday') and ((states.input_datetime.front_sat_start_date_4.state  == states.input_datetime.front_sat_end_date_4.state) or ((states.input_datetime.front_sat_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.front_sat_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"


    front_smtwtfs_4:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.front_sun_4', 'on')  or  
            is_state('binary_sensor.front_mon_4', 'on')  or  
            is_state('binary_sensor.front_tue_4', 'on')  or  
            is_state('binary_sensor.front_wed_4', 'on')  or  
            is_state('binary_sensor.front_thu_4', 'on')  or  
            is_state('binary_sensor.front_fri_4', 'on')  or  
            is_state('binary_sensor.front_sat_4', 'on')   
         }}

    
    front_access_count_4:
      friendly_name: "Access Count"
      value_template: >-
         {{
            (is_state('input_boolean.front_door_accesslimit_4', 'off'))  or  
            (states.input_number.front_door_accesscount_4.state | int > 0)
         }}


    front_door_active_4:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.front_door_enabled_4', 'on')  and  
            is_state('binary_sensor.front_access_count_4', 'on')  and  
            is_state('binary_sensor.front_door_daterange_4', 'on') and
            is_state('binary_sensor.front_smtwtfs_4', 'on')  
         }}
      device_class: connectivity