- id: '1557758650300'
  alias: Start HomeKit
  trigger:
  - event_data: {}
    event_type: zwave.network_complete
    platform: event
  - event_data: {}
    event_type: zwave.network_complete_some_dead
    platform: event
  - event_data: {}
    event_type: zwave.network_ready
    platform: event
  condition: []
  action:
  - service: homekit.start
- id: '1559083319100'
  alias: Z-Wave Test Network
  trigger:
  - at: 03:00
    platform: time
  condition: []
  action:
  - service: zwave.test_network
- id: '1577904430400'
  alias: Dropbox Backup Sync
  description: Synchronize hass.io backup snapshots to Dropbox
  trigger:
  - at: '12:00:00'
    platform: time
  condition:
  - after: '12:00:00'
    before: 02:00:00
    condition: time
    weekday:
    - sun
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
- id: '1578282105600'
  alias: Window - Stairway Blinds Open
  description: ''
  trigger:
  - device_id: 5cd192b226674f6a915e599a744493f7
    domain: deconz
    platform: device
    subtype: open
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
  - entity_id: cover.blinds_stairway
    service: cover.open_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
- id: '1578282135300'
  alias: Window - Stairway Blinds Closed
  description: ''
  trigger:
  - device_id: 5cd192b226674f6a915e599a744493f7
    domain: deconz
    platform: device
    subtype: close
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
  - entity_id: cover.blinds_stairway
    service: cover.close_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
- id: '1578367731900'
  alias: Window - Dining Room Blinds Open
  description: ''
  trigger:
  - device_id: b3791527cb764ca694fc1342ad107d07
    domain: deconz
    platform: device
    subtype: open
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
  - entity_id: cover.blinds_dining_room
    service: cover.open_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
- id: '1578367768100'
  alias: Window - Dining Room Blinds Closed
  description: ''
  trigger:
  - device_id: b3791527cb764ca694fc1342ad107d07
    domain: deconz
    platform: device
    subtype: close
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
  - entity_id: cover.blinds_dining_room
    service: cover.close_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
- id: '1587425847944'
  alias: Roomba S9 - GUI - Start
  description: Start from the GUI when flipping the input
  trigger:
  - entity_id: input_boolean.vacuum_mainfloor_manual
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: script.1587409042440
    service: script.turn_on
- id: '1587425894616'
  alias: Roomba S9 - GUI - Stop
  description: Stop from the GUI when flipping the input
  trigger:
  - entity_id: input_boolean.vacuum_mainfloor_manual
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: script.1587409318603
    service: script.turn_on
