- action:
  - data:
      entity_id: alarm_control_panel.arlohub
    service: alarm_control_panel.alarm_arm_away
  - data:
      entity_id: group.lights
    service: switch.turn_off
  alias: Presence - Departure
  id: '1495333355800'
  trigger:
  - entity_id: group.family_devices
    from: home
    platform: state
    to: not_home
- action:
  - data:
      entity_id: vacuum.roomba
    service: vacuum.stop
  - data:
      data:
        sound: cosmic
      message: Cleaning stopped.
      title: Roomba
    service: notify.pushover
  - data:
      entity_id: vacuum.roomba
    service: vacuum.return_to_base
  alias: Vacuum - Stop
  id: '1495333490008'
  trigger:
  - entity_id: group.family_devices
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.bobbisiphone
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: vacuum.roomba
    state: 'on'
- action:
  - data:
      entity_id: vacuum.roomba
    service: vacuum.turn_on
  - data:
      data:
        sound: cosmic
      message: Cleaning Started
      title: roomba
    service: notify.pushover
  alias: Vacuum - Schedule
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: template
    value_template: '{{ states.sensor.roomba_runtime.state | float < 0.50 }}'
  - after: 08:30:00
    before: '17:00:00'
    condition: time
  - condition: state
    entity_id: binary_sensor.downstairs_occupancy
    state: 'off'
  - condition: state
    entity_id: binary_sensor.master_bedroom_occupancy
    state: 'off'
  id: '1506136149206'
  trigger:
  - entity_id: group.family_devices
    from: home
    platform: state
    to: not_home
- action:
  - data:
      entity_id: alarm_control_panel.arlohub
    service: alarm_control_panel.alarm_arm_home
  alias: Presence - Arrival
  condition: []
  id: '1522516504908'
  trigger:
  - entity_id: group.family_devices
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: script.1522520378551
    service: script.turn_on
  - data:
      entity_id: media_player.everywhere
      message: Jared is home!
    service: tts.google_say
  - data:
      entity_id: script.1522520324671
    service: script.turn_on
  alias: Announcement - Jared Home
  condition:
  - after: '10:00'
    before: '20:00'
    condition: time
  - condition: state
    entity_id: device_tracker.brittanysiphone
    state: home
  id: '1522524371982'
  trigger:
  - entity_id: device_tracker.jaredsrotary
    from: not_home
    platform: state
    to: home
- action:
  - data:
      entity_id: script.1522520378551
    service: script.turn_on
  - data:
      entity_id: media_player.everywhere
      message: Brittany is home!
    service: tts.google_say
  - data:
      entity_id: script.1522520324671
    service: script.turn_on
  alias: Announcement - Brittany Home
  condition:
  - after: '10:00'
    before: '20:00'
    condition: time
  - condition: state
    entity_id: device_tracker.jaredsrotary
    state: home
  id: '1522524618882'
  trigger:
  - entity_id: device_tracker.brittanysiphone
    from: not_home
    platform: state
    to: home
