- id: '1577904430400'
  alias: Dropbox Backup Sync
  description: Synchronize hass.io backup snapshots to Dropbox
  trigger:
  - at: '12:00:00'
    platform: time
  condition:
  - after: '12:00:00'
    before: 02:00:00
    condition: time
    weekday:
    - sun
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
- id: '1578282105600'
  alias: Window - Stairway Blinds Open
  description: ''
  trigger:
  - device_id: 5cd192b226674f6a915e599a744493f7
    domain: deconz
    platform: device
    subtype: open
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
  - entity_id: cover.blinds_stairway
    service: cover.open_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
- id: '1578282135300'
  alias: Window - Stairway Blinds Closed
  description: ''
  trigger:
  - device_id: 5cd192b226674f6a915e599a744493f7
    domain: deconz
    platform: device
    subtype: close
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
  - entity_id: cover.blinds_stairway
    service: cover.close_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_stairway_mode
    service: input_select.select_option
- id: '1578367731900'
  alias: Window - Dining Room Blinds Open
  description: ''
  trigger:
  - device_id: b3791527cb764ca694fc1342ad107d07
    domain: deconz
    platform: device
    subtype: open
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
  - entity_id: cover.blinds_dining_room
    service: cover.open_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
- id: '1578367768100'
  alias: Window - Dining Room Blinds Closed
  description: ''
  trigger:
  - device_id: b3791527cb764ca694fc1342ad107d07
    domain: deconz
    platform: device
    subtype: close
    type: remote_button_short_press
  condition: []
  action:
  - data:
      option: Manual
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
  - entity_id: cover.blinds_dining_room
    service: cover.close_cover
  - delay: 02:00
  - data:
      option: Automatic
    entity_id: input_select.blinds_dining_room_mode
    service: input_select.select_option
- id: '1587425847944'
  alias: Roomba S9 - GUI - Start
  description: Start from the GUI when flipping the input
  trigger:
  - entity_id: input_boolean.vacuum_mainfloor_manual
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: script.1587409042440
    service: script.turn_on
- id: '1587425894616'
  alias: Roomba S9 - GUI - Stop
  description: Stop from the GUI when flipping the input
  trigger:
  - entity_id: input_boolean.vacuum_mainfloor_manual
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: script.1587409318603
    service: script.turn_on
- id: '1589125991236'
  alias: Certificate Renewal
  description: ''
  trigger:
  - below: '11'
    entity_id: sensor.cert_expiry_home_eatsleepbreach_ca
    platform: numeric_state
  condition: []
  action:
  - data:
      addon: core_letsencrypt
    service: hassio.addon_start
- id: '1590940754797'
  alias: Cameras - Re-enable after 1 Hour
  description: ''
  trigger:
  - entity_id: input_boolean.camera_alerts
    platform: state
    to: 'off'
  - entity_id: input_select.camera_person_alerts
    platform: state
    to: Front Door
  - entity_id: input_select.camera_person_alerts
    platform: state
    to: Back Door
  condition: []
  action:
  - delay: 02:00:00
  - data: {}
    entity_id: input_boolean.camera_alerts
    service: input_boolean.turn_on
  - data:
      option: Enabled
    entity_id: input_select.camera_person_alerts
    service: input_select.select_option
- id: '1590940832684'
  alias: Cameras - Input Boolean - Turn Off
  description: ''
  trigger:
  - entity_id: input_boolean.camera_alerts
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      option: Disabled
    entity_id: input_select.camera_motion_alerts
    service: input_select.select_option
  - data:
      option: Disabled
    entity_id: input_select.camera_person_alerts
    service: input_select.select_option
- id: '1590940940768'
  alias: Cameras - Input Boolean - Turn Off
  description: ''
  trigger:
  - entity_id: input_boolean.camera_alerts
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      option: Enabled
    entity_id: input_select.camera_person_alerts
    service: input_select.select_option
- id: '1591375582026'
  alias: Locks - Lock at 10pm
  description: ''
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: lock.front_door
    service: lock.lock
  - data: {}
    entity_id: lock.back_door
    service: lock.lock
  - data: {}
    entity_id: lock.garage_door
    service: lock.lock
- id: '1591481819436'
  alias: Startup - Restart Node-Red
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      addon: a0d7b954_nodered
    service: hassio.addon_restart
