- alias: Sunset Away Lights
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Patio light turned on before sunset.
        data:
          sound: cosmic

- alias: Sunrise Away Lights
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Patio light turned off after sunrise.
        data:
          sound: cosmic

- alias: Patio Off After Arrival
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: switch.patio
      state: 'on'
  action:
    - delay: 00:05:00
    - service: switch.turn_off
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Patio light turned off.
        data:
          sound: cosmic

- alias: Disable Inside Camera
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.netatmo_camera

- alias: Enable Inside Camera
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: switch.turn_on
      entity_id: switch.netatmo_camera