###########################################
# Sunset & Sunrise
###########################################
- alias: Sunset Away Lights
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned on before sunset.
        data:
          sound: cosmic

- alias: Sunrise Away Lights
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned off after sunrise.
        data:
          sound: cosmic

###########################################
# Patio Light
###########################################
- alias: Patio Off After Arrival
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: switch.patio
      state: 'on'
  action:
    - delay: 00:05:00
    - service: switch.turn_off
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned off.
        data:
          sound: cosmic

- alias: Patio On After Departure
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.patio
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned on.
        data:
          sound: cosmic

###########################################
# Inside Camera
###########################################
- alias: Disable Inside Camera
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.netatmo_camera

- alias: Enable Inside Camera
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: switch.turn_on
      entity_id: switch.netatmo_camera

###########################################
# Commute
###########################################
- alias: Commute Notification
  trigger:
    platform: numeric_state
    entity_id: sensor.home_to_enmax    
    above: '25'
  condition:
   - condition: time
     after: '06:50:00'
     before: '07:25:00'
     weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: notify.pushover
      data:
        title: Commute
        message: 'Traffic is heavy, over {{ states.sensor.home_to_enmax.state }} minutes.'
        data:
          sound: cosmic

###########################################
# Roomba
###########################################
- alias: Roomba Schedule
  trigger:
    platform: time
    after: '08:00:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: device_tracker.bobbiiphone_ip
        state: not_home
      - condition: state
        entity_id: device_tracker.family_devices
        state: not_home
  action:
    - service: switch.turn_on
      entity_id: switch.roomba
    - service: notify.pushover
      data:
        title: Roomba
        message: 'Cleaning started.'
        data:
          sound: cosmic

- alias: Roomba Stop
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: switch.roomba
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.roomba
    - service: notify.pushover
      data:
        title: Roomba
        message: 'Cleaning stopped.'
        data:
          sound: cosmic