- id: '1557758650300'
  alias: Start HomeKit
  trigger:
  - event_data: {}
    event_type: zwave.network_complete
    platform: event
  - event_data: {}
    event_type: zwave.network_complete_some_dead
    platform: event
  - event_data: {}
    event_type: zwave.network_ready
    platform: event
  condition: []
  action:
  - service: homekit.start
- id: '1559083319100'
  alias: Z-Wave Test Network
  trigger:
  - at: 03:00
    platform: time
  condition: []
  action:
  - service: zwave.test_network
- id: '1577904430400'
  alias: Dropbox Backup Sync
  description: Synchronize hass.io backup snapshots to Dropbox
  trigger:
  - at: '12:00:00'
    platform: time
  condition:
  - after: '12:00:00'
    before: 02:00:00
    condition: time
    weekday:
    - sun
  action:
  - data:
      addon: 7be23ff5_dropbox_sync
      input:
        command: upload
    service: hassio.addon_stdin
