- action:
  - data:
      entity_id: alarm_control_panel.arlohub
    service: alarm_control_panel.alarm_arm_away
  - data:
      entity_id: group.lights
    service: switch.turn_off
  alias: Presence - Departure
  id: '1495333355800'
  trigger:
  - entity_id: group.family_devices
    from: home
    platform: state
    to: not_home
- action:
  - data:
      entity_id: vacuum.roomba
    service: vacuum.stop
  - data:
      data:
        sound: cosmic
      message: Cleaning stopped.
      title: Roomba
    service: notify.pushover
  - data:
      entity_id: vacuum.roomba
    service: vacuum.return_to_base
  alias: Vacuum - Stop
  id: '1495333490008'
  trigger:
  - entity_id: group.family_devices
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.bobbisiphone
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: vacuum.roomba
    state: 'on'
- id: '1506136149206'
  alias: Vacuum - Schedule
  trigger:
  - entity_id: group.family_devices
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: template
    value_template: '{{ states.sensor.roomba_runtime.state | float < 0.50 }}'
  - after: 07:00:00
    before: '15:00:00'
    condition: time
  action:
  - data:
      entity_id: vacuum.roomba
    service: vacuum.turn_on
  - data:
      data:
        sound: cosmic
      message: Cleaning Started
      title: roomba
    service: notify.pushover
- action:
  - data:
      entity_id: alarm_control_panel.arlohub
    service: alarm_control_panel.alarm_arm_home
  alias: Presence - Arrival
  condition: []
  id: '1522516504908'
  trigger:
  - entity_id: group.family_devices
    from: not_home
    platform: state
    to: home
