###########################################
# Traffic Cams
###########################################
- platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc15.jpg
  name: 'Glenmore & Crowchild'
- platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc27.jpg
  name: 'Glenmore & Macleod'
- platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc56.jpg
  name: 'Bow & 6 Ave'
- platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc5.jpg
  name: '4 Ave & 9 St'
- platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc75.jpg
  name: '5 Ave & 7 St'
- platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=XSM&brand=wui&num=10&delay=100&type=C0R&frame=0&scale=1.000&noclutter=0&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=1&rand=24740140&lat=0&lon=0&label=you
  name: 'YYC Doppler'
- platform: netatmo
  home: Hemlock
  cameras:
    - Kitchen
- platform: local_file
  name: 'Patio'
  file_path: /usr/src/app/capture.png
# - platform: ffmpeg
  # name: 'Patio'
  # ffmpeg_bin: /usr/bin/ffmpeg
  # input: -rtsp_transport tcp -i rtsp://192.168.2.60:554/
  #extra_arguments: -pred 1 -q:v 2
  #extra_arguments: -q:v 2