homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  #http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Edmonton
  #customize must nested within homeassistant entity
  customize: !include customize.yaml

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

http:
  api_password: !secret http_password
  # base_url: !secret base_url
  cors_allowed_origins:
    - !secret base_origin
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 7
  trusted_networks:
    - 192.168.1.0/24

###########################################
# Core Components
###########################################
config:
conversation:
discovery:
history:
ios:
logbook:
logger:
  default: error
map:
recorder:
  purge_keep_days: 7
  purge_interval: 1
sun:
updater:
  include_used_components: true

###########################################
# Includes
###########################################
alert: !include alert.yaml
automation old: !include_dir_merge_list automation
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups_views
input_select: !include input_select.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
switch: !include switch.yaml
vacuum: !include vacuum.yaml

###########################################
# Third Party Platforms
###########################################
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

alarm_control_panel:
  - platform: arlo
    home_mode_name: 'Disarmed'
    away_mode_name: 'Away'

ifttt:
  key: !secret ifttt_api

netatmo:
  api_key: !secret netatmo_apik
  secret_key: !secret netatmo_sk
  username: !secret email_account
  password: !secret netatmo_password

remote:
  - platform: harmony
    name: 'Living Room'
    host: !secret harmony_ip

wink:

wemo:
  static:
    - 192.168.2.15
