homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  #http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Edmonton
  #customize must nested within homeassistant entity
  customize: !include_dir_merge_named customize

# Enables the frontend
frontend:
http:
  api_password: !secret http_password
  # base_url: !secret base_url
  cors_allowed_origins:
    - !secret base_origin
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 7
  trusted_networks:
    - 192.168.1.0/24

# Checks for available updates
updater:
  include_used_components: true
# Auto Discovery
discovery:
# Voice commands
conversation:
# Enables support for tracking state changes over time.
history:
# Retention
recorder:
  purge_days: 7
# View all events in a logbook
logbook:
# Limit debug info
logger:
  default: error
# Track the sun
sun:
# Configuration panel
config:
#iOS
ios:

###########################################
# Includes
###########################################
alert: !include alert.yaml
automation old: !include_dir_merge_list automation
automation: !include automations.yaml
camera: !include camera.yaml
climate: !include climate.yaml
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups_views
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
light: !include light.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
script: !include script.yaml
sensor: !include_dir_merge_list sensor
shell_command: !include shell_command.yaml
switch: !include switch.yaml

###########################################
# Third Party Platforms
###########################################
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt_api

netatmo:
  api_key: !secret netatmo_apik
  secret_key: !secret netatmo_sk
  username: !secret email_account
  password: !secret netatmo_password

remote:
  - platform: harmony
    name: 'Living Room'
    host: !secret harmony_ip

wink:
  #email: !secret email_account
  #password: !secret wink_password
  #client_id: !secret wink_client_id
  #client_secret: !secret wink_client_secret

wemo:
  static:
#    - 192.168.2.15 wemo insight switch
    - 192.168.2.16
    - 192.168.2.14
    - 192.168.2.13
