homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  #http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Edmonton
  #customize must nested within homeassistant entity
  customize: !include customize.yaml

# Enables the frontend
frontend:
  javascript_version: latest
http:
  base_url: !secret base_url
  cors_allowed_origins:
    - !secret base_origin
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy

###########################################
# Core Components
###########################################
config:
discovery:
conversation:
history:
  exclude:
    entities:
      - sensor.family_last_changed
      - sensor.occupancy_last_changed
logbook:
logger:
  default: warning
  # logs:
    # homeassistant.components.homekit: debug
    # pyhap: debug
recorder:
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    entities:
      - sensor.family_last_changed
      - sensor.occupancy_last_changed
updater:
  include_used_components: true

system_health:

###########################################
# Simple Components
###########################################  
map:
sun:
tts:
  - platform: google

###########################################
# Includes
###########################################
alert: !include alert.yaml
automation old: !include_dir_merge_list automation
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
emulated_hue: !include emulated_hue.yaml
group: !include_dir_merge_named groups_views
homekit: !include homekit.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
switch: !include switch.yaml
vacuum: !include vacuum.yaml
zone: !include zone.yaml

###########################################
# iFrame
###########################################
panel_iframe:
  nodered:
    title: 'Node-RED'
    url: 'https://192.168.1.37:1880'
    icon: mdi:resistor-nodes

###########################################
# Third Party Platforms
###########################################
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

alarm_control_panel:
  - platform: arlo
    home_mode_name: 'Home'
    away_mode_name: 'Away'

ecobee:
  api_key: !secret ecobee_api

ifttt:
  key: !secret ifttt_api

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

remote:
  - platform: harmony
    name: 'Living Room'
    host: !secret harmony_ip

wemo:
  static:
    - 192.168.2.15

wink:
  local_control: true
