# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/
http:
  cors_allowed_origins:
    - !secret base_origin
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy

###########################################
# Core Components
###########################################
config:
sun:
discovery:
system_health:
mobile_app:
history: !include history.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
stream:
logger:
  default: warning
updater:
  reporting: false
  include_used_components: true
tts:
  - platform: google_translate
    base_url: !secret base_url

###########################################
# Includes
###########################################
alert: !include alert.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
emulated_hue: !include emulated_hue.yaml
group: !include group.yaml
homekit: !include homekit.yaml
light: !include light.yaml
media_player: !include media_player.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
ios: !include ios.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
    
###########################################
# MQTT
###########################################
mqtt:
  discovery: true
  discovery_prefix: hass
  broker: !secret mqtt_host
  port: 1883
  username: home-assistant
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

###########################################
# Image Processing
###########################################
image_processing:
  - platform: amazon_rekognition
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: us-west-2
    save_file_folder: !secret snapshot_folder
    source:
      - entity_id: camera.front_door_still
      - entity_id: camera.back_door_still

###########################################
# Weather
###########################################
weather:
  - platform: darksky
    api_key: !secret darksky_api
  - platform: environment_canada
    station: !secret ec_station_id

###########################################
# Device Tracker
###########################################
device_tracker:
  - platform: trackr
    username: !secret email_account
    password: !secret trackr_password

###########################################
# Third Party Components
########################################### 
ecobee:
  api_key: !secret ecobee_api

google_assistant: !include google_assistant.yaml

ifttt:
  key: !secret ifttt_api

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

wemo:
  static:
    - !secret wemo_insight_ip