# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes/
http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  cors_allowed_origins:
    - !secret base_origin
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy

###########################################
# Core Components
###########################################
config:
sun:
discovery:
  ignore:
    - plex_mediaserver
    - igd
    - google_cast
    - belkin_wemo
system_health:
mobile_app:
history: !include history.yaml
logbook: !include logbook.yaml
recorder: !include recorder.yaml
logger:
  default: warning
updater:
  reporting: false
  include_used_components: true
tts:
  - platform: google_translate

###########################################
# Includes
###########################################
alert: !include alert.yaml
automation old: !include_dir_merge_list automation
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
emulated_hue: !include emulated_hue.yaml
group: !include group.yaml
homekit: !include homekit.yaml
light: !include light.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
switch: !include switch.yaml

###########################################
# Panels & iFrames
###########################################
panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Map
    sidebar_icon: mdi:access-point-network
    url_path: zwave
    require_admin: true

panel_iframe:
  homebridge:
    title: 'Homebridge'
    url: !secret homebridge_url
    icon: mdi:home-automation
    require_admin: true
  cockpit:
    title: 'Cockpit'
    url: !secret cockpit_url
    icon: mdi:debian
    require_admin: true
    
###########################################
# Home Assistant Community Store (HACS)
###########################################
hacs:
  token: !secret github_token
  theme: true

###########################################
# MQTT
###########################################
mqtt:
  discovery: true
  discovery_prefix: hass
  broker: !secret mqtt_host
  port: 1883
  username: home-assistant
  password: !secret mqtt_password
  # certificate: !secret ssl_ca
  # tls_insecure: true
  # tls_version: auto
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

###########################################
# Image Processing
###########################################
image_processing:
  - platform: amazon_rekognition
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: us-west-2
    target: Person
    source:
      - entity_id: camera.front_door
      - entity_id: camera.back_door
  - platform: doods
    url: "http://192.168.1.15:8181"
    detector: default
    source:
      - entity_id: camera.front_door
      - entity_id: camera.back_door
    file_out:
      - "/config/www/snapshot/{{ camera_entity.split('.')[1] }}_latest.jpg"
    confidence: 50

###########################################
# Weather
###########################################
weather:
  - platform: darksky
    api_key: !secret darksky_api
  - platform: environment_canada
    station: !secret ec_station_id

###########################################
# Media Players
###########################################
cast:
  media_player:
    - host: !secret google_home_office_ip
    - host: !secret google_home_master_bedroom_ip
    - host: !secret google_home_kitchen_ip
    - host: !secret google_home_living_room_ip
    - host: !secret google_home_theater_ip
    - host: !secret chomecast_audio_kitchen_ip
    - host: !secret chomecast_audio_master_bedroom_ip

media_player:
  - platform: samsungtv_custom
    host: !secret samsung_tv_ip
    name: UN65F8000
    sourcelist: '{"AV1": "KEY_AV1", "DVD": "KEY_HDMI2", "ShieldTV": "KEY_HDMI3"}'
  - platform: androidtv
    host: !secret nvidia_shield_ip
    name: Nvidia Shield
    adb_server_ip: !secret advertise_ip
  - platform: gmusic_player
    username: !secret email_account
    password: !secret gmusic_password
    device_id: !secret gmusic_deviceid
    gmusicproxy: !secret gmusic_proxy
  - platform: universal
    name: multi_room_audio
    children:
      - media_player.kitchen_ceiling
      - media_player.master_bedroom_ceiling
      - media_player.google_home_kitchen
      - media_player.google_home_living_room
      - media_player.google_home_office
      - media_player.google_home_master_bedroom
      - media_player.google_home_theater

###########################################
# Device Tracker
###########################################
unifi:
  controllers:
    - host: !secret unifi_ip
      site: !secret unifi_site
      ssid_filter:
        - 'znqp'
        - 'znqp_iot'

device_tracker:
  - platform: trackr
    username: !secret email_account
    password: !secret trackr_password

###########################################
# Third Party Components
########################################### 
cover:
  - platform: myq
    username: !secret email_account
    password: !secret myq_password
    type: chamberlain

ecobee:
  api_key: !secret ecobee_api

google_assistant: !include google_assistant.yaml

ifttt:
  key: !secret ifttt_api

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

remote:
  - platform: harmony
    name: 'Living Room'
    host: !secret harmony_ip

wemo:
  static:
    - !secret wemo_insight_ip