homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  # C for Celsius, F for Fahrenheit
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Edmonton
 
  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret http_password
  cors_allowed_origins:
    - https://riffz.ca

# Checks for available updates
updater:
# Auto Discovery
discovery:
# Voice commands
conversation:
# Enables support for tracking state changes over time.
history:
# Retention
recorder:
  purge_days: 90
# View all events in a logbook
logbook:
# Track the sun
sun:

sensor: !include sensor.yaml
notify: !include notify.yaml
group: !include group.yaml
camera: !include camera.yaml
automation: !include automation.yaml

nest:
  username: !secret email_account
  password: !secret nest_password

ifttt:
  key: !secret ifttt_api

climate:
  platform: nest

netatmo:
  api_key: !secret netatmo_apik
  secret_key: !secret netatmo_sk
  username: !secret email_account
  password: !secret netatmo_password

device_tracker:
  - platform: unifi
    track_new_devices: no
    interval_seconds: 12
    consider_home: 180
    host: 192.168.1.36
    port: 8443
    username: admin
    password: !secret unifi_password
  - platform: bluetooth_tracker

wemo:
  static:
    - 192.168.2.13
    - 192.168.2.14 

switch:
  platform: command_line
  switches:
    roomba:
      command_on: 'node /home/pi/.homeassistant/roomba_clean.js'
      command_off: 'node /home/pi/.homeassistant/roomba_dock.js'
      command_state: 'node /home/pi/.homeassistant/roomba_status.js | grep robot_status | cut -d : -f 4 | cut -f 2 -d "\""'
      value_template: '{{ value == "clean" }}'
