# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages
  external_url: !secret base_origin
  internal_url: !secret internal_url

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
http:
  cors_allowed_origins:
    - !secret base_origin
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret nginx_proxy
    - 172.30.33.0/24

###########################################
# Core Components
###########################################
config:
sun:
discovery:
system_health:
mobile_app:
history:
logbook:
  exclude:
    domains:
      - sun
    entities:
      - sensor.time
      - sensor.time_utc
      - sensor.date_time
      - sensor.time_date
      - sensor.uptime_minutes
      - sensor.watchman_last_updated
    entity_globs:
      - sensor.*_last_seen
      - sensor.rpi_monitor_*
recorder:
  db_url: !secret db_url
stream:
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say
logger:
  default: warning

###########################################
# Includes
###########################################
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
emulated_hue: !include emulated_hue.yaml
media_player: !include media_player.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
template: !include_dir_merge_list template

###########################################
# Classic Groups
###########################################
group:
  family_devices:
    name: "Family Devices"
    entities:
      - person.jared
      - person.brittany
  kitchen_cabinets:
    name: "Kitchen Cabinets"
    entities:
      - light.kitchen_left_led
      - light.kitchen_right_led

###########################################
# Panels
###########################################
panel_iframe:
  frigate:
    title: "Frigate NVR"
    url: !secret frigate_url
    icon: mdi:cctv
    require_admin: true
  zwavejs2mqtt:
    title: "ZwaveJS2Mqtt"
    url: !secret zwavejs_url
    icon: mdi:z-wave
    require_admin: true
  zigbee2mqtt:
    title: "Zigbee2Mqtt"
    url: !secret zigbee_url
    icon: mdi:zigbee
    require_admin: true

###########################################
# Influx
###########################################
influxdb:
  api_version: 2
  host: !secret influx_ip
  ssl: false
  port: 8086
  organization: homeassistant
  bucket: homeassistant
  token: !secret influx_token
  max_retries: 3
  default_measurement: state
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor

###########################################
# Weather
###########################################
weather:
  - platform: darksky
    api_key: !secret darksky_api

###########################################
# Third Party Components
###########################################
google_assistant: !include google_assistant.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

###########################################
# Climate
###########################################
climate:
  - platform: generic_thermostat
    name: Master Bathroom
    heater: switch.space_heater
    target_sensor: sensor.master_bathroom_temperature
    min_temp: 21
    max_temp: 23
    ac_mode: false
    target_temp: 21.5
    min_cycle_duration:
      seconds: 45
    initial_hvac_mode: "off"
    away_temp: 19
    precision: 0.1
