# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  media_dirs:
    snapshot: /config/www/snapshot

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
http:
  cors_allowed_origins:
    - !secret base_origin
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret nginx_proxy
    - 172.30.33.0/24

###########################################
# Core Components
###########################################
config:
sun:
discovery:
system_health:
mobile_app:
history:
logbook:
recorder:
  db_url: !secret db_url
stream:
logger:
  default: warning
updater:
tts:
  - platform: google_translate
    base_url: !secret base_url

###########################################
# Includes
###########################################
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
emulated_hue: !include emulated_hue.yaml
group: !include group.yaml
light: !include light.yaml
media_player: !include media_player.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor

###########################################
# Switch
###########################################
switch:
  platform: deluge
  host: !secret deluge_host
  username: !secret deluge_username
  password: !secret deluge_password

###########################################
# MQTT
###########################################
mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: !secret mqtt_host
  port: 1883
  username: home-assistant
  password: !secret mqtt_password
  birth_message:
    topic: "homeassistant/status"
    payload: "online"
  will_message:
    topic: "homeassistant/status"
    payload: "offline"

###########################################
# Image Processing
###########################################
#image_processing:
#  - platform: amazon_rekognition
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: us-west-2
#    save_file_folder: "/config/www/snapshot/"
#    confidence: 70
#    source:
#      - entity_id: camera.front_door_snapshot
#      - entity_id: camera.back_door_snapshot
#      - entity_id: camera.doorbell_snapshot
#      - entity_id: camera.garage_snapshot

###########################################
# Influx
###########################################
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret http_password
  max_retries: 3
  default_measurement: state
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor

###########################################
# Weather
###########################################
weather:
  - platform: darksky
    api_key: !secret darksky_api
  - platform: environment_canada
    station: !secret ec_station_id

###########################################
# Third Party Components
###########################################
google_assistant: !include google_assistant.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

wemo:
  static:
    - !secret wemo_insight_ip

###########################################
# Climate
###########################################
climate:
  - platform: generic_thermostat
    name: Master Bathroom
    heater: switch.space_heater
    target_sensor: sensor.master_bathroom_temperature
    min_temp: 21
    max_temp: 23
    ac_mode: false
    target_temp: 21.5
    min_cycle_duration:
      seconds: 45
    initial_hvac_mode: "off"
    away_temp: 19
    precision: 0.1

generic_hygrostat:
  - name: Master Bedroom Humidifier
    humidifier: switch.humidifier
    target_sensor: sensor.master_bedroom_multi_sensor_2
    min_humidity: 30
    max_humidity: 50
    target_humidity: 40
    device_class: "humidifier"
    away_humidity: 20
    sensor_stale_duration: 00:45:00
