homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data
  elevation: !secret elevation
  # C for Celsius, F for Fahrenheit
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Edmonton
 
  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret http_password
  cors_allowed_origins:
    - https://riffz.ca

# Checks for available updates
updater:
# Auto Discovery
discovery:
# Voice commands
conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Track the sun
sun:

sensor: !include sensor.yaml
notify: !include notify.yaml
group: !include group.yaml

nest:
  username: !secret email_account
  password: !secret nest_password

wemo:
  static:
    - 192.168.2.13
    - 192.168.2.14 

climate:
  platform: nest

netatmo:
  api_key: !secret netatmo_apik
  secret_key: !secret netatmo_sk
  username: !secret email_account
  password: !secret netatmo_password

camera 1:
  platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc15.jpg
  name: 'Glenmore & Crowchild'
camera 2:
  platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc27.jpg
  name: 'Glenmore & Macleod'
camera 3:
  platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc56.jpg
  name: 'Bow & 6 Ave'
camera 4:
  platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc5.jpg
  name: '4 Ave & 9 St'
camera 5:
  platform: generic
  still_image_url: http://trafficcam.calgary.ca/loc75.jpg
  name: '5 Ave & 7 St'

device_tracker:
  - platform: unifi
    track_new_devices: no
    interval_seconds: 12
    consider_home: 180
    host: 192.168.1.36
    port: 8443
    username: admin
    password: !secret unifi_password
  - platform: bluetooth_tracker

ifttt:
  key: !secret ifttt_api

automation 1:
  alias: Sunset Away Lights
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: notify.pushover
      data:
        message: Patio light turned on before sunset.

automation 2:
  alias: Sunrise Away Lights
  trigger:
    platform: sun
    event: sunrise
    offset: "+01:00:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.patio
    - service: notify.pushover
      data:
        message: Patio light turned off after sunrise.