- platform: unifi
  host: !secret unifi_ip
  username: !secret unifi_user
  password: !secret unifi_password
  ssid_filter:
      - 'znqp'
  verify_ssl: false
  detection_time: 60
  interval_seconds: 10
  consider_home: 180
  track_new_devices: no

- platform: trackr
  username: !secret email_account
  password: !secret trackr_password

#- platform: googlehome
#  host: 192.168.2.34