- platform: unifi
  track_new_devices: no
  interval_seconds: 12
  consider_home: 180
  host: 192.168.1.36
  port: 8443
  username: admin
  password: !secret unifi_password
- platform: bluetooth_tracker