- platform: unifi
  track_new_devices: no
  consider_home: 60
  host: !secret unifi_ip
  port: 8443
  username: !secret unifi_user
  password: !secret unifi_password
  verify_ssl: false
  detection_time: 180

- platform: trackr
  username: !secret email_account
  password: !secret trackr_password
