###########################################
# Home Tab
###########################################
default_view:
  view: yes
  entities:
    - device_tracker.brittanysiphone
    - device_tracker.jaredsrotary
    - sensor.climate_operation_mode
    - sensor.family_room_thermostat_nest_humidity
    - sensor.family_room_thermostat_nest_temperature
    - sensor.co2
    - sensor.scale
    - group.lights
    - group.media
    - group.roomba
    - group.netatmo
    - climate.family_room_nest
    - media_player.my_shield_console
    - alert.roomba_bin_full
    - alert.scale_battery_low

###########################################
# Calgary Tab
###########################################
Calgary:
  view: yes
  name: Calgary
  entities:
    - camera.glenmore__macleod
    - camera.glenmore__crowchild
    - camera.4_ave__9_st
    - camera.5_ave__7_st
    - camera.bow__6_ave
    - sun.sun
    - sensor.yr_temperature
    - sensor.yr_humidity
    - sensor.yr_symbol
    - group.travel
    - group.forecast
    - group.sun_moon
    - group.date_time

###########################################
# System Tab
###########################################
system:
  view: yes
  name: System
  entities:
    - group.system_status
    - group.withings_scale
    - group.wemo_signal
    - group.roomba_system
    - group.wink_hub

###########################################
# Automation Tab
###########################################
automation:
  view: yes
  name: Automation
  entities:
    - group.sunrise_automation
    - group.presence_automation
    - group.arrival_departure_automation
    - group.roomba_automation
    - group.climate_automation
    - group.wink_automation

###########################################
# Home Cards
###########################################
Netatmo:
  name: "Netatmo Welcome"
  entities:
    - switch.netatmo_camera
    - sensor.netatmo_motion
    - camera.hemlock__kitchen

Media:
  entities:
   - sensor.current_activity
   - input_select.harmony
   - switch.livingroomtv
   - switch.shieldtv
   - sensor.tv_schedule

Lights:
  entities:
   - switch.front_door
   - switch.patio
   - switch.bedroom
   - switch.wemo_insight
   - light.bathroom_1
   - light.bathroom_2

Roomba:
  entities:
    - switch.roomba
    - sensor.roomba_cycle_template
    - sensor.roomba_phase_template
    - sensor.roomba_bin_presence_template
    - sensor.roomba_bin_state_template
    - sensor.roomba_runtime
    - sensor.roomba_coverage

###########################################
# Calgary Cards
###########################################
Date_Time:
  name: "Date & Time"
  entities:
    - sensor.date
    - sensor.time

Travel:
  entities:
    - sensor.home_to_enmax
    - sensor.home_to_supported_lifestyles
    - sensor.home_to_acadia
    - sensor.home_to_airport

Forecast:
  entities:
   - sensor.pws_feelslike_c
   - sensor.dark_sky_daily_low_temperature
   - sensor.dark_sky_daily_high_temperature
   - sensor.air_pressure_template
   - sensor.air_quality
   - sensor.uv_rating_template
   - sensor.dark_sky_precip_probability
   - sensor.pws_precip_today_metric
   - sensor.pws_wind_kph
   - camera.yyc_doppler

Sun_Moon:
  name: "Sun & Moon"
  entities:
    - sensor.solar_angle
    - sensor.sunrise
    - sensor.sunset
    - sensor.moon

###########################################
# System Cards
###########################################
System_Status:
  name: "System Status"
  entities:
    - sensor.since_last_boot_templated
    - sensor.connected_clients
    - sensor.hass_release
    - sensor.hass_installed
    - sensor.disk_free_space
    - sensor.cpu_use
    - sensor.ram_use
    - automation.update_notification

Sunrise_Automation:
  name: "Sunrise Automation"
  entities:
    - automation.sunrise_away_lights
    - automation.sunset_away_lights

Presence_Automation:
  name: "Presence Automation"
  entities:
    - automation.off_while_home
    - automation.on_while_home
    - automation.off_while_away
    - automation.on_while_away

Arrival_Departure_Automation:
  name: "Arrival & Departure Automation"
  entities:
    - automation.patio_off_after_arrival
    - automation.patio_on_after_departure
    - automation.commute_notification

Roomba_Automation:
  name: "Roomba Automation"
  entities:
    - automation.roomba_schedule
    - automation.roomba_stop

Climate_Automation:
  name: "Climate Automation"
  entities:
    - automation.heat_on
    - automation.heat_off

Wink_Hub:
  name: "Wink Hub"
  entities:
    - sensor.wink_hub_status
    - sensor.wink_hub_firmware_state_template
    - sensor.wink_hub_firmware_version

Wink_Automation:
  name: "Wink"
  entities:
    - automation.wink_hub_update

Withings_Scale:
  name: "Withings Scale"
  entities:
    - sensor.scale_battery
    - sensor.scale_firmware
 
Wemo_Signal:
  name: "Wemo Signal Strength"
  entities:
    - sensor.front_door_switch_signal
    - sensor.patio_switch_signal
    - sensor.bedroom_switch_signal
    - sensor.insight_switch_signal

Roomba_System:
  name: "Roomba 980"
  entities:
    - sensor.roomba_firmware
    - sensor.roomba_battery
    - sensor.roomba_rssi    
  

###########################################
# Hidden Groups
###########################################
family_devices:
    - device_tracker.brittanysiphone
    - device_tracker.jaredsrotary