- platform: group
  name: Kitchen Cabinets
  entities:
    - light.kitchen_left_led
    - light.kitchen_right_led

- platform: group
  name: Garage Interior
  entities:
    - light.garage_inside_left
    - light.garage_inside_right