###########################################
# Home Sensors
###########################################
- platform: nest
  monitored_conditions:
  - 'temperature'
  - 'humidity'
  - 'mode'
- platform: nzbget
  host: !secret nas_address
  port: 6789
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
  - download_rate

###########################################
# Weather Sensors
###########################################
- platform: yr
  monitored_conditions:
  - 'temperature'
  - 'humidity'
  - 'symbol'
- platform: forecast
  api_key: !secret forecast_api
  monitored_conditions:
  - 'precip_probability'
  - 'temperature_min'
  - 'temperature_max'
- platform: wunderground
  api_key: !secret wunderground_api
  monitored_conditions:
  - 'feelslike_c'
  - 'wind_kph'
  - 'UV'
  - 'precip_today_metric'

###########################################
# Travel Sensors
###########################################
- platform: google_travel_time
  name: Home to Enmax
  api_key: !secret google_maps
  origin: zone.home
  destination: !secret work_address1
- platform: google_travel_time
  name: Home to Supported Lifestyles
  api_key: !secret google_maps
  origin: zone.home
  destination: !secret work_address2
