- platform: command_line
  switches:
    roomba:
      command_on: 'node /home/pi/.homeassistant/roomba/roomba_clean.js'
      command_off: 'node /home/pi/.homeassistant/roomba/roomba_dock.js'
      command_state: 'node /home/pi/.homeassistant/roomba/roomba_status.js | grep robot_status | cut -d : -f 4 | cut -f 2 -d "\""'
      value_template: '{{ value == "clean" }}'
    netatmo_camera:
      command_on: 'bash /home/pi/.homeassistant/netatmo/netatmo_switch.sh on'
      command_off: 'bash /home/pi/.homeassistant/netatmo/netatmo_switch.sh off'
      command_state: 'bash /home/pi/.homeassistant/netatmo/netatmo_status.sh'
      value_template: '{{ value == "on" }}'

- platform: template
  switches:
    livingroomtv:
      value_template: "{{ is_state('media_player.un65f8000', 'on') }}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.un65f8000
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.un65f8000

- platform: template
  switches:
    shieldtv:
      value_template: "{% if states('media_player.my_shield_console') != 'off' %}true{% else %}false{% endif %}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.my_shield_console
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.my_shield_console