- platform: command_line
  switches:
    roomba:
      command_on: "curl -s http://192.168.1.37:8484/api/local/action/start"
      command_off: "curl -s http://192.168.1.37:8484/api/local/action/stop"
      command_state: "curl -s http://192.168.1.37:8484/api/local/info/mission | jq .ok.cycle | sed -e 's/^\"//' -e 's/\"$//'"
      value_template: '{{ value == "clean" }}'
    netatmo_camera:
      command_on: 'bash /config/netatmo/netatmo_switch.sh on'
      command_off: 'bash /config/netatmo/netatmo_switch.sh off'
      command_state: 'bash /config/netatmo/netatmo_status.sh'
      value_template: '{{ value == "on" }}'
    wemo_insight:
      command_on: 'wemo -h 192.168.2.15 -a ON'
      command_off: 'wemo -h 192.168.2.15 -a OFF'
      command_state: 'wemo -h 192.168.2.15 -a GETSTATE'
      value_template: '{{ value == "ON" }}'
    bedroom:
      command_on: 'wemo -h 192.168.2.16 -a ON'
      command_off: 'wemo -h 192.168.2.16 -a OFF'
      command_state: 'wemo -h 192.168.2.16 -a GETSTATE'
      value_template: '{{ value == "ON" }}'
    patio:
      command_on: 'wemo -h 192.168.2.14 -a ON'
      command_off: 'wemo -h 192.168.2.14 -a OFF'
      command_state: 'wemo -h 192.168.2.14 -a GETSTATE'
      value_template: '{{ value == "ON" }}'
    front_door:
      command_on: 'wemo -h 192.168.2.13 -a ON'
      command_off: 'wemo -h 192.168.2.13 -a OFF'
      command_state: 'wemo -h 192.168.2.13 -a GETSTATE'
      value_template: '{{ value == "ON" }}'

- platform: template
  switches:
    livingroomtv:
      value_template: "{{ is_state('media_player.un65f8000', 'on') }}"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.living_room
          command: PowerOn
          device: 40733118
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.un65f8000

- platform: template
  switches:
    shieldtv:
      value_template: "{% if states('media_player.my_shield_console') == 'playing' %}true{% else %}false{% endif %}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.my_shield_console
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.my_shield_console