- platform: mqtt
  name: Guest WiFi
  command_topic: 'wifi/network/guest/switch/set'
  payload_on: "on"
  payload_off: "off"
  state_topic: 'wifi/network/guest/status'
  state_on: "enabled"
  state_off: "disabled"