- platform: template
  switches:
    livingroomtv:
      friendly_name: 'Samsung TV'
      value_template: "{{ is_state('media_player.un65f8000', 'on') }}"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.living_room
          command: PowerOn
          device: 40733118
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.un65f8000

- platform: template
  switches:
    shieldtv:
      friendly_name: 'Nvidia Shield'
      value_template: "{% if states('media_player.my_shield_console') == 'playing' %}true{% else %}false{% endif %}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.my_shield_console
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.my_shield_console

- platform: mqtt
  name: Roomba
  state_topic: 'vacuum/mainfloor/status/cycle'
  command_topic: 'vacuum/mainfloor/switch/set'
  payload_on: "start"
  payload_off: "dock"
  state_on: "clean"
  state_off: "none"
  qos: 0
  retain: true

- platform: mqtt
  name: Guest WiFi
  state_topic: 'wifi/network/guest/status'
  command_topic: 'wifi/network/guest/switch/set'
  payload_on: "on"
  payload_off: "off"
  state_on: "enabled"
  state_off: "disabled"
  qos: 0
  retain: true