- platform: template
  switches:
    livingroomtv:
      friendly_name: 'Samsung TV'
      value_template: "{{ is_state('media_player.un65f8000', 'on') }}"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.living_room
          command: PowerOn
          device: 40733118
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.un65f8000

- platform: template
  switches:
    shieldtv:
      friendly_name: 'Nvidia Shield'
      value_template: "{% if states('media_player.my_shield_console') == 'playing' %}true{% else %}false{% endif %}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.my_shield_console
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.my_shield_console

- platform: template
  switches:
    security_cameras:
      friendly_name: 'Security Cameras'
      value_template: "{% if states('alarm_control_panel.arlohub') == 'disarmed' %}false{% else %}true{% endif %}"
      turn_on:
        service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.arlohub
      turn_off:
        service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.arlohub