- platform: command_line
  switches:
    roomba:
      command_on: 'node /home/pi/.homeassistant/roomba/roomba_clean.js'
      command_off: 'node /home/pi/.homeassistant/roomba/roomba_dock.js'
      command_state: 'node /home/pi/.homeassistant/roomba/roomba_status.js | grep robot_status | cut -d : -f 4 | cut -f 2 -d "\""'
      value_template: '{{ value == "clean" }}'
    netatmo_camera:
      command_on: 'bash /home/pi/.homeassistant/netatmo/netatmo_on.sh'
      command_off: 'bash /home/pi/.homeassistant/netatmo/netatmo_off.sh'
      command_state: 'bash /home/pi/.homeassistant/netatmo/netatmo_status.sh'
      value_template: '{{ value == "on" }}'