
############  input_number:  #####################  
input_number:
  garage_door_accesscount_4:
    name: Access Count
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "Openings Left"

#################  input_datetime:  ##############  
input_datetime:
  garage_end_date_4:
    name: 'End'
    has_time: false
    has_date: true
  garage_start_date_4:
    name: 'Start'
    has_time: false
    has_date: true


  garage_sun_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  garage_sun_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  garage_mon_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  garage_mon_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  garage_tue_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  garage_tue_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  garage_wed_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  garage_wed_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  garage_thu_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  garage_thu_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  garage_fri_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  garage_fri_end_date_4:
    name: 'End'
    has_time: true
    has_date: false

  garage_sat_start_date_4:
    name: 'Start'
    has_time: true
    has_date: false
  garage_sat_end_date_4:
    name: 'End'
    has_time: true
    has_date: false


####################  input_text:  ###############  
input_text:
  garage_door_name_4:
    name: 'Name'
  garage_door_pin_4:
    name: 'PIN'

#################  input_boolean: ################  
input_boolean:
  garage_door_notify_4:
    name: 'Notifications'
  garage_door_daterange_4:
    name: 'Use Date Range'
  garage_door_smtwtfs_4:
    name: 'Use SMTWTFS'
  garage_door_enabled_4:
    name: 'Enabled'
  garage_door_accesslimit_4:
    name: 'Limit Access Count'
    initial: off

  garage_sun_4:
    name: 'Sunday'
    initial: on

  garage_mon_4:
    name: 'Monday'
    initial: on

  garage_tue_4:
    name: 'Tuesday'
    initial: on

  garage_wed_4:
    name: 'Wednesday'
    initial: on

  garage_thu_4:
    name: 'Thursday'
    initial: on

  garage_fri_4:
    name: 'Friday'
    initial: on

  garage_sat_4:
    name: 'Saturday'
    initial: on

################  binary_sensor: #################  
binary_sensor:

- platform: template
  sensors:

    garage_door_enabled_4:
      value_template: "{{ is_state('input_boolean.garage_door_enabled_4', 'on') }}"

    garage_door_daterange_4:
      value_template: "{{ ((is_state('input_boolean.garage_door_daterange_4', 'off') or (states.input_datetime.start_date_4.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string <= now().strftime('%Y%m%d')) and (states.input_datetime.end_date_4.attributes.timestamp| int | timestamp_custom('%Y%m%d', False)|int)|string >=  now().strftime('%Y%m%d'))}}"

    garage_sun_4:
      value_template: "{{ ((is_state('input_boolean.garage_sun_4', 'on'))) and (now().strftime('%A') == 'Sunday') and ((states.input_datetime.garage_sun_start_date_4.state  == states.input_datetime.garage_sun_end_date_4.state) or ((states.input_datetime.garage_sun_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.garage_sun_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    garage_mon_4:
      value_template: "{{ ((is_state('input_boolean.garage_mon_4', 'on'))) and (now().strftime('%A') == 'Monday') and ((states.input_datetime.garage_mon_start_date_4.state  == states.input_datetime.garage_mon_end_date_4.state) or ((states.input_datetime.garage_mon_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.garage_mon_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    garage_tue_4:
      value_template: "{{ ((is_state('input_boolean.garage_tue_4', 'on'))) and (now().strftime('%A') == 'Tuesday') and ((states.input_datetime.garage_tue_start_date_4.state  == states.input_datetime.garage_tue_end_date_4.state) or ((states.input_datetime.garage_tue_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.garage_tue_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    garage_wed_4:
      value_template: "{{ ((is_state('input_boolean.garage_wed_4', 'on'))) and (now().strftime('%A') == 'Wednesday') and ((states.input_datetime.garage_wed_start_date_4.state  == states.input_datetime.garage_wed_end_date_4.state) or ((states.input_datetime.garage_wed_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.garage_wed_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    garage_thu_4:
      value_template: "{{ ((is_state('input_boolean.garage_thu_4', 'on'))) and (now().strftime('%A') == 'Thursday') and ((states.input_datetime.garage_thu_start_date_4.state  == states.input_datetime.garage_thu_end_date_4.state) or ((states.input_datetime.garage_thu_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.garage_thu_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    garage_fri_4:
      value_template: "{{ ((is_state('input_boolean.garage_fri_4', 'on'))) and (now().strftime('%A') == 'Friday') and ((states.input_datetime.garage_fri_start_date_4.state  == states.input_datetime.garage_fri_end_date_4.state) or ((states.input_datetime.garage_fri_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.garage_fri_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"

    garage_sat_4:
      value_template: "{{ ((is_state('input_boolean.garage_sat_4', 'on'))) and (now().strftime('%A') == 'Saturday') and ((states.input_datetime.garage_sat_start_date_4.state  == states.input_datetime.garage_sat_end_date_4.state) or ((states.input_datetime.garage_sat_start_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string <= now().strftime('%H%M') and (states.input_datetime.garage_sat_end_date_4.attributes.timestamp| int | timestamp_custom('%H%M', False)|int)|string >= now().strftime('%H%M'))) }}"


    garage_smtwtfs_4:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.garage_sun_4', 'on')  or  
            is_state('binary_sensor.garage_mon_4', 'on')  or  
            is_state('binary_sensor.garage_tue_4', 'on')  or  
            is_state('binary_sensor.garage_wed_4', 'on')  or  
            is_state('binary_sensor.garage_thu_4', 'on')  or  
            is_state('binary_sensor.garage_fri_4', 'on')  or  
            is_state('binary_sensor.garage_sat_4', 'on')   
         }}

    
    garage_access_count_4:
      friendly_name: "Access Count"
      value_template: >-
         {{
            (is_state('input_boolean.garage_door_accesslimit_4', 'off'))  or  
            (states.input_number.garage_door_accesscount_4.state | int > 0)
         }}


    garage_door_active_4:
      friendly_name: "Status"
      value_template: >-
         {{
            is_state('binary_sensor.garage_door_enabled_4', 'on')  and  
            is_state('binary_sensor.garage_access_count_4', 'on')  and  
            is_state('binary_sensor.garage_door_daterange_4', 'on') and
            is_state('binary_sensor.garage_smtwtfs_4', 'on')  
         }}
      device_class: connectivity