##################################################  
################  COMMON ENTITIES  ###############  
##################################################  

###################  sensor:  ####################  
sensor:
- platform: template
  sensors:
    garage_door_report:
      friendly_name: 'Door Status'
      value_template: >
          {% set number = states('sensor.lock_garage_door_deadbolt_alarm_level') %}
          {% set alarm_type_value = states('sensor.lock_garage_door_deadbolt_alarm_type') %}
          {% set entity_id = 'input_text.garage_door_name_' + number %}
          {% set user = 'Master' if number == '0' else states(entity_id) %}
          {% set alarm_type_value = '24' if (as_timestamp(now())-as_timestamp(states.lock.garage_door_lock.last_changed)) < 15 and (as_timestamp(now())-as_timestamp(states.sensor.lock_garage_door_deadbolt_alarm_type.last_changed)) > 15  and (states.lock.lock_garage_door_lock.state) == 'locked' else alarm_type_value %}
          {% set alarm_type_value = '25' if (as_timestamp(now())-as_timestamp(states.lock.garage_door_lock.last_changed)) < 15 and (as_timestamp(now())-as_timestamp(states.sensor.lock_garage_door_deadbolt_alarm_type.last_changed)) > 15  and (states.lock.lock_garage_door_lock.state) == 'unlocked' else alarm_type_value %}
          {% set alarm_type_general_actions = {
            '0':'No Status Reported',          
            '9':'Lock Jammed',
            '17':'Keypad Lock Jammed',
            '21':'Manual Lock',
            '22':'Manual Unlock',
            '23':'HA Lock Jammed',
            '24':'HA Lock',
            '25':'HA Unlock',
            '26':'Auto Lock Jammed',
            '27':'Auto Lock',
            '32':'All Codes Deleted',
            '161':'Bad Code Entered',
            '167':'Battery Low',
            '168':'Battery Critical',
            '169':'Battery Too Low To Operate Lock' } %}
          {% set alarm_type_lock_actions = {
            '18':'Keypad Lock',
            '19':'Keypad Unlock',
            '162':'Lock Code Attempt Outside of Schedule' } %}
          {% set alarm_type_code_actions = {
            '33':'Code Deleted',
            '112':'Code Changed',
            '113':'Duplicate Code' } %}
          {% if alarm_type_value in alarm_type_code_actions %}
            {{ alarm_type_code_actions[alarm_type_value] }} (Code {{ number}})
          {% elif alarm_type_value in alarm_type_lock_actions and number == '0' %}
            {{ alarm_type_lock_actions[alarm_type_value] }} with Schlage Button
          {% elif alarm_type_value in alarm_type_lock_actions  %}
            {{ alarm_type_lock_actions[alarm_type_value] }} with Code {{ number }} ({{ user }})
          {% elif alarm_type_value in alarm_type_general_actions %}
            {{ alarm_type_general_actions[alarm_type_value] }}
          {% else %}
            Unknown Alarm Type Value {{ states('sensor.lock_garage_door_deadbolt_alarm_type') }}
          {% endif %}

    garage_door_code:
      friendly_name: 'Last Entry'
      value_template: >
        {% set number = states('sensor.lock_garage_door_deadbolt_alarm_level') %}
        {% set entity_id = 'input_text.garage_door_name_' + number %}
        {% set user = 'Master' if number == '0' else states(entity_id) %}
        {{ user }}
        
    garage_door_lock_battery:
       value_template: '{{ state_attr("zwave.lock_garage_door_deadbolt","battery_level")|round }}'
       friendly_name: "Garage Door Lock Battery"
       unit_of_measurement: '%'
       device_class: battery 

###################  input_select:  #################### 
input_select:
  lock_zwave_option_3_garage:
      name: Enable or disable the beeper.
      options:
          - Enable Beeper
          - Disable Beeper
  lock_zwave_option_4_garage:
      name: Prevents all user codes from unlocking the deadbolt
      options:
          - Disable Vacation Mode
          - Enable Vacation Mode
  lock_zwave_option_5_garage:
      name: Press the Outside Schlage Button to lock the deadbolt
      options:
          - Enable Lock & Leave
          - Disable Lock & Leave
  lock_zwave_option_7_garage:
      name: Alarm sounds based on door activity
      options:
          - Alarm Off
          - Activity
          - Tamper
          - Forced Entry
  lock_zwave_option_8_garage:
      name: Activity Alarm Sensitivity
      options:
          - Medium Sensitivity
          - Most Sensitive
          - Medium/high Sensitivity
          - Medium/low Sensitivity
          - Least Sensitivity
  lock_zwave_option_9_garage:
      name: Tamper Alarm Sensitivity
      options:
          - Medium Sensitivity
          - Most Sensitive
          - Medium/high Sensitivity
          - Medium/low Sensitivity
          - Least Sensitivity
  lock_zwave_option_10_garage:
      name: Forced Entry Alarm Sensitivity
      options:
          - Medium Sensitivity
          - Most Sensitive
          - Medium/high Sensitivity
          - Medium/low Sensitivity
          - Least Sensitivity
  lock_zwave_option_11_garage:
      name: Disable Local Alarm Controls
      options:
          - Enable local alarm controls
          - Disable local alarm controls
  lock_zwave_option_15_garage:
      name: Auto lock
      options:
          - Disable auto lock
          - Enable auto lock
  lock_zwave_option_16_garage:
      name: User code pin length (changing Length erases all codes)
      options:
          - 4
          - 5
          - 6
          - 7
          - 8

###################  automation:  ####################  
automation:
  - alias: Garage Lock - Decrement Access Count
    trigger:
      platform: state
      entity_id: sensor.garage_door_report
    condition:
      condition: template
      value_template: >-
        {% set report = states.sensor.garage_door_report.state %}
        {% set codeslot = (report | regex_findall_index('(\d+)', ignorecase=True)) %}
        {% set codetext = 'garage_door_notify_' + codeslot | string %}
        {% set codetext = 'garage_door_accesslimit_' + codeslot | string %}
        {% set code = states['input_boolean'][codetext].state %}
        {% set unlocked = ( report| regex_match('Keypad Unlock with Code ' + codeslot, ignorecase=True) ) %}
        {{ (code == "on") and unlocked }}
    action:
      - service: input_number.set_value
        data_template:
          entity_id: >-
            {% set report = states.sensor.garage_door_report.state %}
            {% set codeslot = (report | regex_findall_index('(\d+)', ignorecase=True)) %}
            {{ 'input_number.garage_door_accesscount_' + codeslot | string }}
          value: >-
            {% set report = states.sensor.garage_door_report.state %}
            {% set codeslot = (report | regex_findall_index('(\d+)', ignorecase=True)) %}
            {% set codetext = 'garage_door_accesscount_' + codeslot | string %}
            {% set accesscount = states['input_number'][codetext].state | int %}
            {{ (accesscount - 1) }}
  
  - alias: Garage Lock - Access Notification
    trigger:
      platform: state
      entity_id: sensor.garage_door_report
    condition:
      condition: template
      value_template: >-
         {% set report = states.sensor.garage_door_report.state %}
         {% set codeslot = (report | regex_findall_index('(\d+)', ignorecase=True)) %}
         {% set codetext = 'garage_door_notify_' + codeslot | string %}
         {% set code = states['input_boolean'][codetext].state %}
         {{ code == "on" }}
    action:
      - service: notify.notify
        data_template:
           title: "Garage Door"
           message: >-
              {{ states.sensor.garage_door_report.state }}
           
  - alias: Garage Lock - Add Code
    trigger:
      entity_id: binary_sensor.garage_door_active_1, binary_sensor.garage_door_active_2, binary_sensor.garage_door_active_3, binary_sensor.garage_door_active_4, binary_sensor.garage_door_active_5, binary_sensor.garage_door_active_6 
      platform: state
      to: 'on'
    action:
      - service: lock.set_usercode
        data_template:
          node_id: >- 
              {{states.lock.garage_door_lock.attributes.node_id}}
          code_slot: >-
              {% set object_id = trigger.to_state.object_id %}
              {% set code_slot = object_id[18:] %}
              {{ code_slot  }}
          usercode: >-
              {% set object_id = trigger.to_state.object_id %}
              {% set code_slot = object_id[18:] %}    
              {% set codetext = 'garage_door_pin_' + code_slot | string %}
              {% set code = states['input_text'][codetext].state %}
              {{ code | string }}
  
  - alias: Garage Lock - Update Code
    trigger:
      entity_id: input_text.garage_door_pin_1, input_text.garage_door_pin_2, input_text.garage_door_pin_3, input_text.garage_door_pin_4, input_text.garage_door_pin_5, input_text.garage_door_pin_6
      platform: state
    condition:
      condition: template
      value_template: >-
          {{  trigger.from_state.state != trigger.to_state.state }}
    action:
      - service: persistent_notification.create
        data_template:
          title: "Garage Door Lock"
          message: >-
            {% set object_id = trigger.to_state.object_id %}
            {% set codeslot = object_id[15:] %}
            {{ 'You changed the PIN for code ' + codeslot | string + '. Please enable it in order to make it active.'}}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {% set object_id = trigger.to_state.object_id %}
            {% set codeslot = object_id[15:] %}
            {{ 'input_boolean.garage_door_enabled_' + codeslot | string }}
  
  - alias: Garage Lock - Clear Code
    trigger:
      entity_id: binary_sensor.garage_door_active_1, binary_sensor.garage_door_active_2, binary_sensor.garage_door_active_3, binary_sensor.garage_door_active_4,binary_sensor.garage_door_active_5, binary_sensor.garage_door_active_6 
      platform: state
      to: 'off'
    action:
      - service: lock.set_usercode
        data_template:
          node_id: >- 
              {{states.lock.garage_door_lock.attributes.node_id}}
          code_slot: >-
              {% set object_id = trigger.to_state.object_id %}
              {% set code_slot = object_id[18:] %}
              {{ code_slot  }}
          usercode: >-
              {{ range(1000, 9999) | random | int }}
  
  - alias: Garage Lock - Set Options
    trigger:
      - platform: state
        entity_id:
          - input_select.lock_zwave_option_3_garage
          - input_select.lock_zwave_option_4_garage
          - input_select.lock_zwave_option_5_garage
          - input_select.lock_zwave_option_7_garage
          - input_select.lock_zwave_option_8_garage
          - input_select.lock_zwave_option_9_garage
          - input_select.lock_zwave_option_10_garage
          - input_select.lock_zwave_option_11_garage
          - input_select.lock_zwave_option_15_garage
          - input_select.lock_zwave_option_16_garage
    action:
      - service: zwave.set_config_parameter
        data_template:
          # Garage Door Deadbolt.  You must put in the zwave node id's here 
          node_id: 16
          parameter: >-
            {% if trigger.entity_id == 'input_select.lock_zwave_option_3_garage' %}
              3
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_4_garage' %}
              4
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_5_garage' %}
              5
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_7_garage' %}
              7
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_8_garage' %}
              8
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_9_garage' %}
              9
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_10_garage' %}
              10
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_11_garage' %}
              11
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_15_garage' %}
              15
            {% elif trigger.entity_id == 'input_select.lock_zwave_option_16_garage' %}
              16
            {% else %}
              0
            {% endif %}
          value: >-
            {{ trigger.to_state.state }}

