###########################################
# Automation
###########################################
automation.presence__arrival__patio_off:
  icon: mdi:home
automation.presence__departure__patio_on:
  icon: mdi:city

automation.sunset__patio__turn_off:
  icon: mdi:weather-sunset-up
automation.sunset__patio__turn_on:
  icon: mdi:weather-sunset-down

automation.presence__arrival__turn_off:
  icon: mdi:home
automation.presence__arrival__turn_on:
  icon: mdi:home

automation.presence__departure__turn_off:
  icon: mdi:city
automation.presence__departure__turn_on:
  icon: mdi:city

automation.weather__alert__state_change:
  icon: mdi:message-alert
