###########################################
# Automation
###########################################
automation.sunrise_away_lights:
  icon: mdi:weather-sunset-up
automation.sunset_away_lights:
  icon: mdi:weather-sunset-down

automation.patio_off_after_arrival:
  icon: mdi:login
automation.patio_on_after_departure:
  icon: mdi:logout

automation.roomba_schedule:
  icon: mdi:play-circle
automation.roomba_stop:
  icon: mdi:stop-circle

automation.off_while_home:
  icon: mdi:home
automation.on_while_home:
  icon: mdi:home

automation.off_while_away:
  icon: mdi:city
automation.on_while_away:
  icon: mdi:city

automation.heat_on:
  icon: mdi:nest-thermostat
automation.heat_off:
  icon: mdi:nest-thermostat

automation.commute_notification:
  icon: mdi:car

automation.update_notification:
  icon: mdi:message-alert