- platform: template
  sensors:
    netatmo_motion:
      value_template: >-
        {%- if is_state("binary_sensor.kitchen_motion", "on") %}
            Detected
        {% elif is_state("binary_sensor.kitchen_motion", "off") %}
            Quiet
        {% else %}
            n/a
        {%- endif %}

- platform: arlo

- platform: template
  sensors:
    backyard_camera_battery_template:
      friendly_name: "Backyard Camera Battery"
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.camera.backyard.attributes.battery_level %}
          {{ states.camera.backyard.attributes.battery_level|round }}
        {% else %}
          {{ states.camera.backyard.attributes.battery_level }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("states.camera.backyard.attributes.battery_level", "unknown") %}
          mdi:battery-unknown
        {% elif states('sensor.backyard_camera_battery_template') | float <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.backyard_camera_battery_template') | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.sensor.backyard_camera_battery_template.state|float / 10)|round*10}}
        {% endif %}

- platform: template
  sensors:
    front_door_camera_battery_template:
      friendly_name: "Front Door Camera Battery"
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.camera.front_door.attributes.battery_level %}
          {{ states.camera.front_door.attributes.battery_level|round }}
        {% else %}
          {{ states.camera.front_door.attributes.battery_level }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("states.camera.front_door.attributes.battery_level", "unknown") %}
          mdi:battery-unknown
        {% elif states('sensor.front_door_camera_battery_template') | float <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.front_door_camera_battery_template') | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.sensor.front_door_camera_battery_template.state|float / 10)|round*10}}
        {% endif %}