- platform: arlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength

- platform: template
  sensors:
    patio_camera_battery_template:
      friendly_name: "Patio Camera Battery"
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.camera.patio.attributes.battery_level %}
          {{ states.camera.patio.attributes.battery_level|round }}
        {% else %}
          {{ states.camera.patio.attributes.battery_level }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("states.camera.patio.attributes.battery_level", "unknown") %}
          mdi:battery-unknown
        {% elif states('sensor.patio_camera_battery_template') | float <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.patio_camera_battery_template') | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.sensor.patio_camera_battery_template.state|float / 10)|round*10}}
        {% endif %}

- platform: template
  sensors:
    front_door_camera_battery_template:
      friendly_name: "Front Door Camera Battery"
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.camera.front_door.attributes.battery_level %}
          {{ states.camera.front_door.attributes.battery_level|round }}
        {% else %}
          {{ states.camera.front_door.attributes.battery_level }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("states.camera.front_door.attributes.battery_level", "unknown") %}
          mdi:battery-unknown
        {% elif states('sensor.front_door_camera_battery_template') | float <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.front_door_camera_battery_template') | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.sensor.front_door_camera_battery_template.state|float / 10)|round*10}}
        {% endif %}

- platform: template
  sensors:
    kitchen_camera_battery_template:
      friendly_name: "Kitchen Camera Battery"
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.camera.kitchen.attributes.battery_level %}
          {{ states.camera.kitchen.attributes.battery_level|round }}
        {% else %}
          {{ states.camera.kitchen.attributes.battery_level }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("states.camera.kitchen.attributes.battery_level", "unknown") %}
          mdi:battery-unknown
        {% elif states('sensor.kitchen_camera_battery_template') | float <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.kitchen_camera_battery_template') | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.sensor.kitchen_camera_battery_template.state|float / 10)|round*10}}
        {% endif %}