###########################################
# Climate
###########################################
- platform: template
  sensors:
    climate_operation_mode:
      value_template: "{{ states.climate.family_room_nest.attributes.operation_mode if states.climate.family_room_nest is not none else 'Unknown' }}"
      entity_id: climate.family_room_nest