###########################################
# Climate
###########################################
- platform: template
  sensors:
    climate_operation_mode:
      value_template: "{{ states.climate.main_floor.attributes.operation_mode if states.climate.main_floor is not none else 'Unknown' }}"
      entity_id: climate.main_floor