###########################################
# Climate
###########################################
- platform: template
  sensors:
    climate_operation_mode:
      value_template: "{{ states.climate.main_floor.attributes.climate_mode if states.climate.main_floor is not none else 'Unknown' }}"

- platform: template
  sensors:
    climate_preset_mode:
      value_template: "{{ states.climate.main_floor.attributes.preset_mode if states.climate.main_floor is not none else 'Unknown' }}"

- platform: template
  sensors:
    climate_main_floor_temperature:
      friendly_name: 'Main Floor Temperature'
      unit_of_measurement: '°C'
      value_template: '{{ states.climate.main_floor.attributes.current_temperature }}'