###########################################
# Dryer
###########################################
- platform: template
  sensors:
    dryer_run_state:
      friendly_name: 'Run State'
      value_template: '{{ states.sensor.dryer.attributes.run_state }}'

- platform: template
  sensors:
    dryer_pre_state:
      friendly_name: 'Pre State'
      value_template: '{{ states.sensor.dryer.attributes.pre_state }}'

- platform: template
  sensors:
    dryer_initial_time:
      friendly_name: 'Initial Time'
      value_template: '{{ states.sensor.dryer.attributes.initial_time }}'

- platform: template
  sensors:
    dryer_remaining_time:
      friendly_name: 'Remaining Time'
      value_template: '{{ states.sensor.dryer.attributes.remain_time }}'

- platform: template
  sensors:
    dryer_reserve_time:
      friendly_name: 'Reserve Time'
      value_template: '{{ states.sensor.dryer.attributes.reserve_time }}'

- platform: template
  sensors:
    dryer_current_course:
      friendly_name: 'Current Course'
      value_template: '{{ states.sensor.dryer.attributes.current_course }}'

- platform: template
  sensors:
    dryer_tempcontrol_option_state:
      friendly_name: 'Temperature Control'
      value_template: '{{ states.sensor.dryer.attributes.tempcontrol_option_state }}'

- platform: template
  sensors:
    dryer_drylevel_option_state:
      friendly_name: 'Dry Level'
      value_template: '{{ states.sensor.dryer.attributes.drylevel_option_state }}'