###########################################
# Washer
###########################################
- platform: template
  sensors:
    washer_run_state:
      friendly_name: 'Run State'
      value_template: '{{ states.sensor.washer.attributes.run_state }}'

- platform: template
  sensors:
    washer_pre_state:
      friendly_name: 'Pre State'
      value_template: '{{ states.sensor.washer.attributes.pre_state }}'

- platform: template
  sensors:
    washer_initial_time:
      friendly_name: 'Initial Time'
      value_template: '{{ states.sensor.washer.attributes.initial_time }}'
      
- platform: template
  sensors:
    washer_reserve_time:
      friendly_name: 'Reserve Time'
      value_template: '{{ states.sensor.washer.attributes.reserve_time }}'

- platform: template
  sensors:
    washer_current_course:
      friendly_name: 'Current Course'
      value_template: '{{ states.sensor.washer.attributes.current_course }}'

- platform: template
  sensors:
    washer_spin_option_state:
      friendly_name: 'Spin Speed'
      value_template: '{{ states.sensor.washer.attributes.spin_speed }}'

- platform: template
  sensors:
    washer_watertemp_option_state:
      friendly_name: 'Water Temperature'
      value_template: '{{ states.sensor.washer.attributes.water_temp }}'

- platform: template
  sensors:
    washer_tubclean_count:
      friendly_name: 'Tub Clean Count'
      value_template: '{{ states.sensor.washer.attributes.tubclean_count }}'

- platform: template
  sensors:
    washer_childlock_mode:
      friendly_name: 'Child Lock'
      value_template: '{{ states.sensor.washer.attributes.child_lock }}'

- platform: template
  sensors:
    washer_steam_mode:
      friendly_name: 'Steam Mode'
      value_template: '{{ states.sensor.washer.attributes.steam }}'

- platform: template
  sensors:
    washer_doorlock_mode:
      friendly_name: 'Door Lock'
      value_template: '{{ states.sensor.washer.attributes.door_lock }}'

- platform: template
  sensors:
    washer_prewash_mode:
      friendly_name: 'Prewash'
      value_template: '{{ states.sensor.washer.attributes.pre_wash }}'

- platform: template
  sensors:
    washer_turbowash_mode:
      friendly_name: 'Turbo Wash'
      value_template: '{{ states.sensor.washer.attributes.turbo_wash }}'

- platform: template
  sensors:
    washer_remotestart_mode:
      friendly_name: 'Remote Start'
      value_template: '{{ states.sensor.washer.attributes.remote_start }}'

- platform: template
  sensors:
    washer_state:
      friendly_name: 'Washer State'
      value_template: '{{ state_attr("sensor.washer", "run_state") }}'
      icon_template: mdi:washing-machine      
    washer_program_length:
      friendly_name: 'Washer Program Length'
      value_template: >-
        {% set washerprogramminutes = (states.sensor.washer.attributes.initial_time.split(':')[0]|int * 60) + (states.sensor.washer.attributes.initial_time.split(':')[1] | int) %}
        {{ washerprogramminutes }}
      icon_template: mdi:washing-machine      
    washer_remaining_time:
      friendly_name: 'Washer Remaining Time'
      value_template: >-
        {% set washerremainminutes = (states.sensor.washer.attributes.remain_time.split(':')[0]|int * 60) + (states.sensor.washer.attributes.remain_time.split(':')[1] | int) %}
        {{ washerremainminutes }}
      icon_template: mdi:washing-machine
    washer_progress:
      friendly_name: 'Washer Progress'
      value_template: >-
        {% if (states.sensor.washer_program_length.state | int) < 1 %}
          0
        {% else %}          
          {% set washerprogress = (100 - (((states.sensor.washer_remaining_time.state | int) / (states.sensor.washer_program_length.state | int)) * 100)) %}
          {{ washerprogress }}
        {% endif %}             
      icon_template: mdi:dishwasher