###########################################
# Media
###########################################
- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret nas_address
  port: 8989
  days: 7
  urlbase: /sonarr
  ssl: false
  max: 5

- platform: radarr_upcoming_media
  api_key: !secret radarr_api
  host: !secret nas_address
  port: 7878
  days: 60
  ssl: false
  theaters: true
  max: 5

- platform: template
  sensors:
    amp_wattage:
      friendly_name: 'Watts'
      value_template: >- 
        {%- if states.switch.wemo_outlet_1.attributes.current_power_w %}
          {{ states.switch.wemo_outlet_1.attributes.current_power_w|round }}
        {% else %}
          0
        {%- endif %}
      unit_of_measurement: 'W'