###########################################
# Media
###########################################
- platform: sonarr
  api_key: !secret sonarr_api
  host: !secret nas_address
  port: 8989
  monitored_conditions:
  - upcoming
  days: 1

- platform: template
  sensors:
    tv_schedule:
      friendly_name: 'TV Today'
      value_template: >-
        {%- for attr in states.sensor.sonarr_upcoming.attributes -%}
        {%- if not attr=="friendly_name" and not attr=="icon" and not attr=="unit_of_measurement" -%}
        {{attr}}{% if not loop.last %}, {% endif %}
        {%- endif -%}
        {%- endfor -%}

- platform: template
  sensors:
    amp_wattage:
      friendly_name: 'Watts'
      value_template: >- 
        {%- if states.switch.wemo_outlet_1.attributes.current_power_w %}
          {{ states.switch.wemo_outlet_1.attributes.current_power_w|round }}
        {% else %}
          0
        {%- endif %}
      unit_of_measurement: 'W'