###########################################
# Room Sensors
###########################################
- platform: template
  sensors:
    master_bedroom_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.master_bedroom_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.master_bedroom_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    downstairs_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.downstairs_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.downstairs_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}