###########################################
# Room Sensors
###########################################
- platform: template
  sensors:
    master_bedroom_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.master_bedroom_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.master_bedroom_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    theater_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.theater_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.theater_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    office_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.office_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.office_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}
        icon_template: >-
          {%- if is_state("binary_sensor.office_occupancy", "on") %}
              mdi:run-fast
          {%- elif is_state("binary_sensor.office_occupancy", "off") %}
              mdi:run
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    living_room_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.living_room_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.living_room_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    guest_bedroom_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.guest_bedroom_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.guest_bedroom_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    master_bathroom_occupancy:
        value_template: >-
          {%- if is_state("binary_sensor.master_bathroom_occupancy", "on") %}
              Occupied
          {%- elif is_state("binary_sensor.master_bathroom_occupancy", "off") %}
              Unoccupied
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    family_last_changed:
      value_template: "{{ relative_time(states.group.family_devices.last_changed).split(' ')[0] }}"

- platform: template
  sensors:
    occupancy_last_changed:
      value_template: "{{ relative_time(states.group.binary_occupancy.last_changed).split(' ')[0] }}"