###########################################
# Pet Sensors
###########################################
- platform: template
  sensors:
    alfred_last_seen_template:
      friendly_name: 'Last Seen'
      value_template: "{{ states.device_tracker.alfie.attributes.last_seen }}"

- platform: template
  sensors:
    alfred_trackr_battery_template:
      friendly_name: "Battery"
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.device_tracker.alfie.attributes.battery_level %}
          {{ states.device_tracker.alfie.attributes.battery_level|round }}
        {% else %}
          {{ states.device_tracker.alfie.attributes.battery_level }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("sensor.alfred_trackr_battery_template", "unknown") %}
          mdi:battery-unknown
        {% elif states('sensor.alfred_trackr_battery_template') | float <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.alfred_trackr_battery_template') | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.device_tracker.alfie.attributes.battery_level|float / 10)|round*10}}
        {% endif %}
