###########################################
# Printer Queue
###########################################
- platform: scrape
  name: "Printer Queue"
  resource: !secret printq_url
  authentication: basic
  username: !secret printq_user
  password: !secret printq_pass
  select: "body > div.body > div > table > tbody > tr > td:nth-child(5)"