###########################################
# RadonEye RD200 Setup
###########################################
# sudo apt-get install git python-pip libglib2.0-dev
# git clone https://github.com/ceandre/radonreader.git
# sudo pip install paho-mqtt bluepy
# sudo hciconfig hci0 up
# sudo hcitool lescan
# Edit radon_reader.py to lower QoS to 0
# nano /home/pi/radonreader/radon_reader.py
# crontab -e
# */10 * * * * python /home/pi/radonreader/radon_reader.py -a FB:80:0C:9D:8A:07 --mqtt -ma -ms <hostname> -mp 1883 -mu <username> -mw <password> -v

- platform: mqtt
  name: "Radon Level"
  state_topic: "environment/RADONEYE/9D-8A-07" # <-- last three octets of the MAC
  unit_of_measurement: "pCi/L"
  value_template: "{{ value_json.radonvalue }}"
  unique_id: "RadonEye9D8A07" # <-- last three octets of the MAC 
  force_update: true
  expire_after: 1200 # If no response in 20 mins mark the sensor as Unavailible
  icon: mdi:radioactive
  qos: 0

- platform: template
  sensors:
    radon_becquerels:
      value_template: '{{ ((states.sensor.radon_level.state | float * 37)) | round(0) | default(0) }}'
      friendly_name: 'Radon Becquerels'
      unit_of_measurement: 'Bq/m3'