###########################################
# Roomba
###########################################
- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Cycle'
  value_template: '{{ value_json.ok.cycle }}'
  
- platform: template
  sensors:
    roomba_cycle_template:
        value_template: >-
          {%- if is_state("sensor.roomba_cycle", "charge") %}
              Docked
          {%- elif is_state("sensor.roomba_cycle", "clean") %}
              Cleaning
          {%- elif is_state("sensor.roomba_cycle", "stuck") %}
              Stuck
          {%- elif is_state("sensor.roomba_cycle", "stop") %}
              Stopped
          {%- else %}
              None
          {%- endif %}

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Phase'
  value_template: '{{ value_json.ok.phase }}'

- platform: template
  sensors:
    roomba_phase_template:
        value_template: >-
          {%- if is_state("sensor.roomba_phase", "charge") %}
              Charging
          {%- elif is_state("sensor.roomba_phase", "run") %}
              Cleaning
          {%- elif is_state("sensor.roomba_phase", "stuck") %}
              Stuck
          {%- elif is_state("sensor.roomba_phase", "stop") %}
              Stopped
          {%- else %}
              None
          {%- endif %}

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba NotReady Flag'
  value_template: '{{ value_json.ok.notReady }}'
  
- platform: template
  sensors:
    roomba_notready_template:
      value_template: >
        {% if is_state("sensor.roomba_notready_flag", "0") %}
          Ready
        {% elif is_state("sensor.roomba_notready_flag", "1") %}
          Cliff
        {% elif is_state("sensor.roomba_notready_flag", "2") %}
          Wheels Dropped
        {% elif is_state("sensor.roomba_notready_flag", "3") %}
          Left Wheel Dropped
        {% elif is_state("sensor.roomba_notready_flag", "4") %}
          Right Wheel Dropped
        {% elif is_state("sensor.roomba_notready_flag", "7") %}
          Bin Missing
        {% elif is_state("sensor.roomba_notready_flag", "15") %}
          Low Battery
        {% elif is_state("sensor.roomba_notready_flag", "16") %}
          Tilted
        {% elif is_state("sensor.roomba_notready_flag", "18") %}
          Docking Failed
        {% else %}
          Error
        {% endif %}

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Battery'
  value_template: '{{ value_json.ok.batPct }}'
  unit_of_measurement: '%'
  scan_interval: 60

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Coverage'
  value_template: '{{ value_json.ok.sqft }}'
  unit_of_measurement: 'sqft'
  scan_interval: 60

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Maintenance Flag'
  value_template: '{{ value_json.ok.flags }}'
  scan_interval: 60

- platform: template
  sensors:
    roomba_maintenance_template:
      value_template: >
        {% if is_state("sensor.roomba_maintenance_flag", "0") %}
            Ready
        {% elif is_state("sensor.roomba_maintenance_flag", "1") %}
            Bin Full
        {% elif is_state("sensor.roomba_maintenance_flag", "2") %}
            Bin Detached
        {% elif is_state("sensor.roomba_maintenance_flag", "4") %}
            Ready
        {% elif is_state("sensor.roomba_maintenance_flag", "5") %}
            Bin Full
        {% elif is_state("sensor.roomba_maintenance_flag", "6") %}
            Bin Detached
        {% elif is_state("sensor.roomba_maintenance_flag", "12") %}
            Starting
        {% else %}
            n/a
        {% endif %}

- platform: history_stats
  name: Roomba Runtime
  entity_id: switch.roomba
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'