###########################################
# Roomba
###########################################
- platform: command_line
  command: "node /home/pi/.homeassistant/roomba/roomba_status.js | grep robot_status | cut -d : -f 5 | cut -f 1 -d \",\" | sed -e 's/^\"//' -e 's/\"$//'"
  name: 'Roomba Phase'

- platform: template
  sensors:
    roomba_status:
        value_template: >-
          {%- if is_state("sensor.roomba_phase", "charge") %}
              Docked
          {% elif is_state("sensor.roomba_phase", "run") %}
              Cleaning
          {% elif is_state("sensor.roomba_phase", "stuck") %}
              Stuck
          {% else %}
              n/a
          {%- endif %}

- platform: command_line
  command: "node /home/pi/.homeassistant/roomba/roomba_status.js | grep robot_status | cut -d : -f 11 | cut -f 1 -d \",\""
  name: 'Roomba Battery'
  unit_of_measurement: '%'
  scan_interval: 60

- platform: command_line
  command: "node /home/pi/.homeassistant/roomba/roomba_status.js | grep robot_status | cut -d : -f 17 | sed 's/[^0-9]*//g'"
  name: 'Roomba Coverage'
  unit_of_measurement: 'sqft'
  scan_interval: 60

- platform: command_line
  command: "node /home/pi/.homeassistant/roomba/roomba_status.js | grep robot_status | cut -d : -f 3 | sed 's/[^0-9]*//g'"
  name: 'Roomba Maintenance Flag'
  scan_interval: 60

- platform: template
  sensors:
    roomba_maintenance_template:
      value_template: >
        {% if is_state("sensor.roomba_maintenance_flag", "0" or "4") %}
            Ready
        {% elif is_state("sensor.roomba_maintenance_flag", "1") %}
            Bin Full
        {% elif is_state("sensor.roomba_maintenance_flag", "12") %}
            Starting
        {% else %}
            n/a
        {% endif %}