###########################################
# Roomba
###########################################
- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Cycle'
  value_template: '{{ value_json.cleanMissionStatus.cycle }}'
  
- platform: template
  sensors:
    roomba_cycle_template:
        value_template: >-
          {%- if is_state("sensor.roomba_cycle", "charge") %}
              Docked
          {%- elif is_state("sensor.roomba_cycle", "clean") %}
              Cleaning
          {%- elif is_state("sensor.roomba_cycle", "stuck") %}
              Stuck
          {%- elif is_state("sensor.roomba_cycle", "stop") %}
              Stopped
          {%- else %}
              None
          {%- endif %}

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Phase'
  value_template: '{{ value_json.cleanMissionStatus.phase }}'

- platform: template
  sensors:
    roomba_phase_template:
        value_template: >-
          {%- if is_state("sensor.roomba_phase", "charge") %}
              Charging
          {%- elif is_state("sensor.roomba_phase", "run") %}
              Cleaning
          {%- elif is_state("sensor.roomba_phase", "stuck") %}
              Stuck
          {%- elif is_state("sensor.roomba_phase", "stop") %}
              Stopped
          {%- else %}
              None
          {%- endif %}

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba NotReady Flag'
  value_template: '{{ value_json.cleanMissionStatus.notReady }}'
  
- platform: template
  sensors:
    roomba_notready_template:
      value_template: >
        {% if is_state("sensor.roomba_notready_flag", "0") %}
          Ready
        {% elif is_state("sensor.roomba_notready_flag", "1") %}
          Cliff
        {% elif is_state("sensor.roomba_notready_flag", "2") %}
          Wheels Stuck
        {% elif is_state("sensor.roomba_notready_flag", "3") %}
          Left Wheel Stuck
        {% elif is_state("sensor.roomba_notready_flag", "4") %}
          Right Wheel Stuck
        {% elif is_state("sensor.roomba_notready_flag", "7") %}
          Bin Missing
        {% elif is_state("sensor.roomba_notready_flag", "15") %}
          Low Battery
        {% elif is_state("sensor.roomba_notready_flag", "16") %}
          Tilted
        {% elif is_state("sensor.roomba_notready_flag", "18") %}
          Docking Failed
        {% else %}
          Error
        {% endif %}

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Battery'
  value_template: '{{ value_json.batPct }}'
  unit_of_measurement: '%'
  scan_interval: 60

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/mission
  name: 'Roomba Coverage'
  value_template: '{{ value_json.cleanMissionStatus.sqft }}'
  unit_of_measurement: 'sqft'
  scan_interval: 60

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/sys
  name: 'Roomba Bin Presence'
  value_template: '{{ value_json.bin.present}}'
  scan_interval: 60

- platform: template
  sensors:
    roomba_bin_presence_template:
        value_template: >-
          {%- if is_state("sensor.roomba_bin_presence", "True") %}
              Attached
          {%- elif is_state("sensor.roomba_bin_presence", "False") %}
              Ejected
          {%- else %}
              Offline
          {%- endif %}
 
- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/sys
  name: 'Roomba Bin State'
  value_template: '{{ value_json.bin.full}}'
  scan_interval: 60

- platform: template
  sensors:
    roomba_bin_state_template:
        value_template: >-
          {%- if is_state("sensor.roomba_bin_state", "False") %}
              Empty
          {%- elif is_state("sensor.roomba_bin_state", "True") %}
              Full
          {%- else %}
              Offline
          {%- endif %}

- platform: history_stats
  name: Roomba Runtime
  entity_id: switch.roomba
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/sys
  name: 'Roomba Firmware'
  value_template: '{{ value_json.softwareVer }}'
  scan_interval: 60

- platform: rest
  resource: http://192.168.1.37:8484/api/local/info/state
  name: 'Roomba RSSI'
  value_template: '{{ value_json.signal.rssi }}'
  scan_interval: 60