###########################################
# Roomba
###########################################
- platform: template
  sensors:
    roomba_cycle_template:
      friendly_name: 'Cycle'
      value_template: >-
        {%- if "states.vacuum.roomba.attributes.status", "Charging" %}
          Docked
        {%- elif "states.vacuum.roomba.attributes.status", "Running" %}
          Cleaning
        {%- elif "states.vacuum.roomba.attributes.status", "Stuck" %}
          Stuck
        {%- elif "states.vacuum.roomba.attributes.status", "Stopped" %}
          Stopped
        {%- else %}
          None
        {%- endif %}

- platform: template
  sensors:
    roomba_battery_template:
      friendly_name: "Battery"
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.vacuum.roomba.attributes.battery_level %}
          {{ states.vacuum.roomba.attributes.battery_level|round }}
        {% else %}
          {{ states.vacuum.roomba.attributes.battery_level }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("sensor.roomba_cycle_template", "Docked") %}
          mdi:battery-charging
        {% elif states('sensor.roomba_battery_template') | float <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.roomba_battery_template') | float >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states.sensor.roomba_battery_template.state|float / 10)|round*10}}
        {% endif %}

- platform: template
  sensors:
    roomba_bin_presence_template:
      friendly_name: 'Bin Status'
      value_template: >-
        {%- if "states.vacuum.roomba.attributes.bin_present", "true" %}
            Attached
        {%- elif "states.vacuum.roomba.attributes.bin_present", "false" %}
            Ejected
        {%- else %}
            Offline
        {%- endif %}

- platform: template
  sensors:
    roomba_bin_state_template:
      friendly_name: 'Bin State'
      value_template: >-
        {%- if "states.vacuum.roomba.attributes.bin_full", "false" %}
            Empty
        {%- elif "states.vacuum.roomba.attributes.bin_present", "true" %}
            Full
        {%- else %}
            Offline
        {%- endif %}

- platform: template
  sensors:
    roomba_firmware_template:
      friendly_name: 'Firmware'
      value_template: '{{ states.vacuum.roomba.attributes.software_version }}'

- platform: history_stats
  name: Roomba Runtime
  entity_id: vacuum.roomba
  state: 'on'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
