###########################################
# Sun & Moon Sensors
###########################################
- platform: template
  sensors:
    day_night:
      friendly_name: 'Day/Night'
      value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
      icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'

- platform: template
  sensors:
    solar_angle:
      value_template: '{{ states.sun.sun.attributes.elevation }}'
      friendly_name: 'Solar Angle'
      unit_of_measurement: 'degrees'
    sunrise:
      value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_rising)) | timestamp_local) [11:16] }} am'
      friendly_name: 'Sunrise'
    sunset:
      value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_setting)-(43200)) | timestamp_local) [11:16] }} pm'
      friendly_name: 'Sunset'

- platform: moon

- platform: season
  type: astronomical

- platform: template
  sensors:
    season_template:
      friendly_name: "Season"
      value_template: >-
        {%- if is_state("sensor.season", "Spring") %}
          Spring
        {%- elif is_state("sensor.season", "Summer") %}
          Summer
        {%- elif is_state("sensor.season", "Autumn") %}
          Autumn
        {%- elif is_state("sensor.season", "Winter") %}
          Winter
        {% else %}
          None
        {% endif %}
      icon_template: >-
        {%- if is_state("sensor.season", "Spring") %}
          mdi:weather-sunset
        {%- elif is_state("sensor.season", "Summer") %}
          mdi:weather-sunny
        {%- elif is_state("sensor.season", "Autumn") %}
          mdi:leaf
        {%- elif is_state("sensor.season", "Winter") %}
          mdi:weather-snowy
        {% else %}
          mdi:weather-snowy-rainy
        {% endif %}
