###########################################
# System Sensors
###########################################
- platform: api_streams

- platform: version

- platform: rest
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  username: !secret email_account
  password: !secret github_token
  authentication: basic
  value_template: '{{ value_json.tag_name }}'
  name: 'HASS Release'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor

- platform: command_line
  command: "df -h | grep none | awk '{print $4}'"
  name: "Disk Free Space"
  scan_interval: 60

- platform: systemmonitor
  resources:
    - type: since_last_boot
    - type: memory_use_percent
    - type: processor_use

- platform: uptime