###########################################
# System Sensors
###########################################
- platform: version

- platform: authenticated
  enable_notification: false
  exclude:
    - 172.30.32.2
    - 172.30.33.0
    - 172.30.33.1
    - 172.30.33.2
    - 172.30.33.3
    - 172.30.33.4
    - 172.30.33.5

- platform: template
  sensors:
    last_successful_authentication_hostname:
      value_template: '{{ states.sensor.last_successful_authentication.attributes.hostname }}'
    last_successful_authentication_username:
      value_template: '{{ states.sensor.last_successful_authentication.attributes.username }}'

- platform: rest
  resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
  username: !secret email_account
  password: !secret github_token
  authentication: basic
  value_template: '{{ value_json.tag_name }}'
  name: 'HASS Release'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor

- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: processor_use
    - type: disk_use_percent
      arg: /

- platform: uptime

- platform: mqtt
  name: "Zwave Controller Status"
  state_topic: "hass/nodeID_1/status"
  value_template: "{{ value_json.status }}"

- platform: mqtt
  name: "Zwave Controller Last Activity"
  state_topic: "hass/nodeID_1/status"
  value_template: "{{ value_json.time | multiply(0.001) | round(0) | timestamp_local }}"

- platform: mqtt
  name: "Zwave Controller Notification"
  state_topic: "hass/_EVENTS/ZWAVE_GATEWAY-hass/notification"
  value_template: "{{ value_json.data[2] }}"