#from https://github.com/renemarc/home-assistant-config/blob/master/sensors/atmosphere.yaml
- platform: template
  sensors:
    aqi_friendly:
      friendly_name: "Air Quality Index"
      icon_template: "mdi:chemical-weapon"
      value_template: >-
        {% set index = states('sensor.u_s_air_quality_index') | float(-1) %}
        {% if index > 300 %}
          Hazardous
        {% elif index > 200 %}
          Very Unhealthy
        {% elif index > 150 %}
          Unhealthy
        {% elif index > 100 %}
          Heightened
        {% elif index > 50 %}
          Moderate
        {% elif index >= 0 %}
          Good
        {% else %}
          unknown
        {% endif %}

###########################################
# Templates
###########################################
- platform: template
  sensors:
    air_pressure_template:
      friendly_name: "Air Pressure"
      value_template: "{% if states('sensor.tempest_st_00084235_station_pressure') | float <= 980 %}Low{% elif states('sensor.tempest_st_00084235_station_pressure') | float >= 1000 %}Good{% elif states('sensor.tempest_st_00084235_station_pressure') | float >= 1020 %}High{% else %}n/a{% endif %}"

- platform: template
  sensors:
    precip_probability_template:
      friendly_name: "Chance of Precipitation"
      unit_of_measurement: "%"
      value_template: "{{ state_attr('weather.calgary_olympic_park','forecast')[0].precipitation_probability|float|round }}"