###########################################
# Tomorrow's Forecast Sensors
###########################################
- platform: template
  sensors:
    air_pressure_tomorrow_template:
      friendly_name: 'Air Pressure'
      value_template: "{% if states('sensor.dark_sky_pressure_1d') | float <= 980 %}Low{% elif states('sensor.dark_sky_pressure_1d') | float >= 1000 %}Good{% elif states('sensor.dark_sky_pressure_1d') | float >= 1020 %}High{% else %}n/a{% endif %}"

- platform: template
  sensors:
    dark_sky_precip_type_tomorrow_template:
      friendly_name: "Precipitation"
      value_template: >-
        {%- if is_state("sensor.dark_sky_precip_1d", "rain") %}
          Rain
        {%- elif is_state("sensor.dark_sky_precip_1d", "snow") %}
          Snow
        {%- elif is_state("sensor.dark_sky_precip_1d", "hail") %}
          Hail
        {%- elif is_state("sensor.dark_sky_precip_1d", "snowy-rainy") %}
          Snowy Rain
        {% else %}
          None
        {% endif %}
      icon_template: >-
        {%- if is_state("sensor.dark_sky_precip_1d", "rain") %}
          mdi:weather-rainy
        {%- elif is_state("sensor.dark_sky_precip_1d", "snow") %}
          mdi:weather-snowy
        {%- elif is_state("sensor.dark_sky_precip_1d", "hail") %}
          mdi:weather-hail
        {%- elif is_state("sensor.dark_sky_precip_1d", "snowy-rainy") %}
          mdi:snowy-rainy
        {% else %}
          mdi:weather-sunny
        {% endif %}

- platform: template
  sensors:
    dark_sky_precip_probability_tomorrow_template:
      friendly_name: 'Chance of Precipitation'
      unit_of_measurement: "%"
      value_template: >-
        {%- if states.sensor.dark_sky_precip_probability_1d.state %}
          {{ states.sensor.dark_sky_precip_probability_1d.state|round }}
        {% else %}
          {{ states.sensor.dark_sky_precip_probability_1d.state }}
        {%- endif %}
      icon_template: >-
        {%- if is_state("sensor.dark_sky_precip_1d", "rain") %}
          mdi:weather-rainy
        {%- elif is_state("sensor.dark_sky_precip_1d", "snow") %}
          mdi:weather-snowy
        {%- elif is_state("sensor.dark_sky_precip_1d", "hail") %}
          mdi:weather-hail
        {%- elif is_state("sensor.dark_sky_precip_1d", "snowy-rainy") %}
          mdi:snowy-rainy
        {% else %}
          mdi:weather-sunny
        {% endif %}

- platform: template
  sensors:
    dark_sky_wind_bearing_tomorrow_template:
      friendly_name: 'Wind Direction'
      value_template: >-
        {%if states.sensor.dark_sky_wind_bearing_1d.state | float<=11 %}North
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float>348 %}North
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=34 | float>11 %}North North East
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=56 | float>34 %}North East
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=79 | float>56 %}East North East
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=101 | float>79 %}East
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=124 | float>101 %}East South East
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=146 | float>124 %}South East
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=169 | float>146 %}South South East
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=191 | float>169 %}South
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=214 | float>191 %}South South West
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=236 | float>214 %}South West
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=259 | float>236 %}West South West
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=281 | float>259 %}West
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=304 | float>281 %}West North West
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=326 | float>304 %}West North West
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=348 | float>326 %}North North West
        {%- endif %}
