- platform: plex
  sensors:
  host: !secret nas_address
  username: !secret email_account
  password: !secret plex_password
  server: nas

- platform: template
  sensors: 
    tv_schedule:
      value_template: >-
        {%- for attr in states.sensor.sonarr_upcoming.attributes -%}
        {%- if not attr=="friendly_name" and not attr=="icon" and not attr=="unit_of_measurement" -%}
        {{attr}}{% if not loop.last %}, {% endif %}
        {%- endif -%}
        {%- endfor -%}

- platform: template
  sensors:
    now_playing_template:
      friendly_name: 'Now Playing'
      #value_template: '{{ states.media_player.my_shield_console.attributes.media_title }}'
      value_template: >-
        {%- if is_state("{{ states.media_player.my_shield_console }}", "playing") %}
          {{ states.media_player.my_shield_console.attributes.media_title }}
        {%- elif is_state("sensor.current_activity", "Watch TV") %}
          Cable
        {%- else %}
          None
        {%- endif %}