###########################################
# Roomba
###########################################
- platform: mqtt
  name: "Vacuum Mainfloor Cycle"
  state_topic: "vacuum/mainfloor/status/cycle"
  force_update: true

- platform: mqtt
  name: "Vacuum Mainfloor Phase"
  state_topic: "vacuum/mainfloor/status/phase"
  force_update: true

- platform: mqtt
  name: "Vacuum Mainfloor BinFull"
  state_topic: "vacuum/mainfloor/status/binfull"
  force_update: true
  
- platform: mqtt
  name: "Vacuum Mainfloor BinPresent"
  state_topic: "vacuum/mainfloor/status/binpresent"
  force_update: true

- platform: mqtt
  name: "Vacuum Mainfloor BatPct"
  state_topic: "vacuum/mainfloor/status/batpct"
  force_update: true
  unit_of_measurement: '%'
  device_class: battery

- platform: template
  sensors:
    roomba_cycle_template:
      friendly_name: 'Cycle'
      value_template: >-
        {%- if is_state('sensor.vacuum_mainfloor_phase', 'charge') %}
            Docked
        {%- elif is_state('sensor.vacuum_mainfloor_phase', 'hmUsrDock') %}
            Docking
        {%- elif is_state('sensor.vacuum_mainfloor_cycle', 'clean') %}
            Cleaning
        {%- else %}
            Offline
        {%- endif %}
  
- platform: template
  sensors:
    roomba_bin_state_template:
      friendly_name: 'Bin State'
      value_template: >-
        {%- if is_state('sensor.vacuum_mainfloor_binfull', 'true') %}
            Full
        {%- elif is_state('sensor.vacuum_mainfloor_binfull', 'false') %}
            Empty
        {%- else %}
            Offline
        {%- endif %}

- platform: template
  sensors:
    roomba_bin_presence_template:
      friendly_name: 'Bin Status'
      value_template: >-
        {%- if "sensor.vacuum_mainfloor_binpresent", "true" %}
            Attached
        {%- elif "sensor.vacuum_mainfloor_binpresent", "false" %}
            Ejected
        {%- else %}
            Offline
        {%- endif %}

- platform: history_stats
  name: Roomba Runtime
  entity_id: sensor.vacuum_mainfloor_cycle
  state: 'clean'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
