###########################################
# Vacuum - Upstairs
###########################################
- platform: template
  sensors:
    vacuum_upstairs_status:
      friendly_name: 'Upstairs Vacuum Status'
      value_template: "{{ state_attr('vacuum.upstairs', 'status') }}"

- platform: template
  sensors:
    vacuum_upstairs_bin_presence:
      friendly_name: 'Upstairs Vacuum Bin Present'
      value_template: >-
        {%- if is_state_attr('vacuum.upstairs','bin_present',false) %}
            Detached
        {%- elif is_state_attr('vacuum.upstairs','bin_present',true) %}
            Attached
        {%- else %}
            Unknown
        {%- endif %}

- platform: history_stats
  name: Vacuum Upstairs Runtime
  entity_id: vacuum.upstairs
  state: 'cleaning'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

###########################################
# Vacuum - Main Floor
###########################################
- platform: template
  sensors:
    vacuum_main_floor_status:
      friendly_name: 'Main Floor Vacuum Status'
      value_template: "{{ state_attr('vacuum.main_floor', 'status') }}"

- platform: template
  sensors:
    vacuum_main_floor_bin_presence:
      friendly_name: 'Main Floor Vacuum Bin Present'
      value_template: >-
        {%- if is_state_attr('vacuum.main_floor','bin_present',false) %}
            Detached
        {%- elif is_state_attr('vacuum.main_floor','bin_present',true) %}
            Attached
        {%- else %}
            Unknown
        {%- endif %}

- platform: history_stats
  name: Vacuum Main Floor Runtime
  entity_id: vacuum.main_floor
  state: 'cleaning'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

###########################################
# Mop - Main Floor
###########################################
- platform: template
  sensors:
    vacuum_main_floor_mop_status:
      friendly_name: 'Main Floor Mop Status'
      value_template: "{{ state_attr('vacuum.main_floor_mop', 'status') }}"

- platform: template
  sensors:
    vacuum_main_floor_mop_pad:
      friendly_name: 'Main Floor Mop Pad'
      value_template: "{{ state_attr('vacuum.main_floor_mop', 'detected_pad') }}"

- platform: template
  sensors:
    vacuum_main_mop_tank_presence:
      friendly_name: 'Main Floor Mop Tank Present'
      value_template: >-
        {%- if is_state_attr('vacuum.main_floor_mop','tank_present',false) %}
            Detached
        {%- elif is_state_attr('vacuum.main_floor_mop','tank_present',true) %}
            Attached
        {%- else %}
            Unknown
        {%- endif %}

- platform: template
  sensors:
    vacuum_main_mop_lid_state:
      friendly_name: 'Main Floor Mop Lid State'
      value_template: >-
        {%- if is_state_attr('vacuum.main_floor_mop','lid_closed',false) %}
            Open
        {%- elif is_state_attr('vacuum.main_floor_mop','lid_closed',true) %}
            Closed
        {%- else %}
            Unknown
        {%- endif %}

- platform: template
  sensors:
    vacuum_main_floor_mop_tank_level:
      friendly_name: 'Main Floor Mop Tank Level'
      value_template: "{{ state_attr('vacuum.main_floor_mop', 'tank_level') }}"

- platform: history_stats
  name: Main Floor Mop Runtime
  entity_id: vacuum.main_floor_mop
  state: 'cleaning'
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'