###########################################
# Weather Sensors
###########################################
- platform: yr
  monitored_conditions:
  - 'temperature'
  - 'humidity'
  - 'symbol'

- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
  - 'precip_probability'
  - 'temperature_min'
  - 'temperature_max'
  - 'pressure'

- platform: template
  sensors:
    air_pressure_template:
      value_template: "{% if states('sensor.dark_sky_pressure') | float <= 980 %}Low{% elif states('sensor.dark_sky_pressure') | float >= 1000 %}Good{% elif states('sensor.dark_sky_pressure') | float >= 1020 %}High{% else %}n/a{% endif %}"

- platform: wunderground
  api_key: !secret wunderground_api
  monitored_conditions:
  - 'feelslike_c'
  - 'wind_kph'
  - 'UV'
  - 'precip_today_metric'

- platform: template
  sensors:
    uv_rating_template:
      value_template: "{% if states('sensor.pws_uv') | float <= 2 %}Low{% elif states('sensor.pws_uv') | float >= 3 %}Moderate{% elif states('sensor.pws_uv') | float >= 6 %}High{% elif states('sensor.pws_uv') | float >= 9 %}Extreme{% else %}n/a{% endif %}"  

- platform: template
  sensors:
    solar_angle:
      value_template: '{{ states.sun.sun.attributes.elevation }}'
      friendly_name: 'Solar Angle'
      unit_of_measurement: 'degrees'
    sunrise:
      value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_rising)) | timestamp_local) [11:16] }} am'
      friendly_name: 'Sunrise'
    sunset:
      value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_setting)-(43200)) | timestamp_local) [11:16] }} pm'
      friendly_name: 'Sunset'

- platform: waqi
  locations:
    - calgary
- platform: template
  sensors:
    air_quality:
      value_template: "{% if states('sensor.waqi_calgary_central_2_alberta') | float <= 50 %}Good{% elif states('sensor.waqi_calgary_central_2_alberta') | float >= 51 %}Moderate{% elif states('sensor.waqi_calgary_central_2_alberta') | float >= 101%}Poor{% elif states('sensor.waqi_calgary_central_2_alberta') | float >= 151%}Bad{% elif states('sensor.waqi_calgary_central_2_alberta') | float >= 201%}Unhealthy{% elif states('sensor.waqi_calgary_central_2_alberta') | float >= 301%}Dangerous{% else %}n/a{% endif %}"