###########################################
# Wemo Signal
###########################################
- platform: command_line
  unit_of_measurement: '%'
  command: 'wemo -h 192.168.2.15 -a GETSIGNALSTRENGTH'
  name: 'Insight Switch Signal'
  scan_interval: 60

- platform: command_line
  unit_of_measurement: '%'
  command: 'wemo -h 192.168.2.16 -a GETSIGNALSTRENGTH'
  name: 'Bedroom Switch Signal'
  scan_interval: 60

- platform: command_line
  unit_of_measurement: '%'
  command: 'wemo -h 192.168.2.14 -a GETSIGNALSTRENGTH'
  name: 'Patio Switch Signal'
  scan_interval: 60

- platform: command_line
  unit_of_measurement: '%'
  command: 'wemo -h 192.168.2.13 -a GETSIGNALSTRENGTH'
  name: 'Front Door Switch Signal'
  scan_interval: 60