- platform: template
  sensors:
    dining_room_window_template:
      friendly_name: 'Dining Room Window'
      value_template: >-
        {%- if is_state('binary_sensor.dining_room_window', 'off') %}
            Closed
        {%- elif is_state('binary_sensor.dining_room_window', 'on') %}
            Open
        {%- else %}
            Offline
        {%- endif %}
      icon_template: >-
        {%- if is_state('binary_sensor.dining_room_window', 'off') %}
          mdi:window-closed
        {%- elif is_state('binary_sensor.dining_room_window', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}

- platform: template
  sensors:
    master_bedroom_window_template:
      friendly_name: 'Master Bedroom Window'
      value_template: >-
        {%- if is_state('binary_sensor.master_bedroom_window', 'off') %}
            Closed
        {%- elif is_state('binary_sensor.master_bedroom_window', 'on') %}
            Open
        {%- else %}
            Offline
        {%- endif %}
      icon_template: >-
        {%- if is_state('binary_sensor.master_bedroom_window', 'off') %}
          mdi:window-closed
        {%- elif is_state('binary_sensor.master_bedroom_window', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}

- platform: template
  sensors:
    office_window_template:
      friendly_name: 'Office Window'
      value_template: >-
        {%- if is_state('binary_sensor.office_window', 'off') %}
            Closed
        {%- elif is_state('binary_sensor.office_window', 'on') %}
            Open
        {%- else %}
            Offline
        {%- endif %}
      icon_template: >-
        {%- if is_state('binary_sensor.office_window', 'off') %}
          mdi:window-closed
        {%- elif is_state('binary_sensor.office_window', 'on') %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
