###########################################
# Wink Sensors
###########################################
- platform: template
  sensors:
    wink_hub_status:
      friendly_name: 'Status'
      value_template: >-
        {%- if is_state("binary_sensor.wink_hub", "on") %}
            Online
        {%- elif is_state("binary_sensor.wink_hub", "unavailable") %}
            Offline
        {%- else %}
            Error
        {%- endif %}

- platform: template
  sensors:
    wink_hub_firmware_version:
      friendly_name: 'Firmware Version'
      value_template: '{{ states.binary_sensor.wink_hub.attributes["firmware version"] }}'

- platform: template
  sensors:
    wink_hub_firmware_state:
      value_template: '{{ states.binary_sensor.wink_hub.attributes["update needed"] }}'

- platform: template
  sensors:
    wink_hub_firmware_state_template:
      friendly_name: 'Firmware State'
      value_template: >-
        {%- if is_state("sensor.wink_hub_firmware_state", "False") %}
            Up-to-Date
        {%- elif is_state("sensor.wink_hub_firmware_state", "True") %}
            Update Available
        {%- else %}
            Error
        {%- endif %}
