###########################################
# Withings
###########################################
- platform: command_line
  unit_of_measurement: 'ppm'
  command: 'bash /config/withings/withings_co2.sh'
  name: 'CO2'
  scan_interval: 60

- platform: command_line
  unit_of_measurement: 'C'
  command: 'bash /config/withings/withings_temp.sh'
  name: 'Scale'
  scan_interval: 60

- platform: command_line
  unit_of_measurement: '%'
  command: 'bash /config/withings/withings_battery.sh'
  name: 'Scale Battery'
  scan_interval: 60

- platform: command_line
  command: 'bash /config/withings/withings_firmware.sh'
  name: 'Scale Firmware'
  scan_interval: 60

- platform: template
  sensors:
    scale_battery_low:
      value_template: "{% if states('sensor.scale_battery') | float <= 15 %}true{% elif states('sensor.scale_battery') | float >= 16 %}false{% else %}n/a{% endif %}"