###########################################
# Withings
###########################################
- platform: command_line
  unit_of_measurement: 'ppm'
  command: 'bash /home/pi/.homeassistant/withings/withings_co2.sh'
  name: 'CO2'
  scan_interval: 60

- platform: command_line
  unit_of_measurement: 'C'
  command: 'bash /home/pi/.homeassistant/withings/withings_temp.sh'
  name: 'Scale'
  scan_interval: 60