###########################################
# Climate
###########################################
- alias: Heat On
  trigger:
    platform: state
    entity_id: climate.family_room_nest
    state: '21.0'
  action:
    - service: climate.set_operation_mode
      data:
        operation_mode: heat
    - service: climate.set_temperature
      data:
        temperature: 25.0
    - service: notify.pushover
      data:
        title: Thermostat
        message: 'Turned on, inside {{ states.climate.family_room_nest.attributes.current_temperature }}C'
        data:
          sound: cosmic

- alias: Heat Off
  trigger:
    platform: state
    entity_id: climate.family_room_nest
    state: '24.0'
  action:
    - service: climate.set_operation_mode
      data:
        operation_mode: eco
    - service: climate.set_temperature
      data:
        temperature: 18.0
    - service: notify.pushover
      data:
        title: Thermostat
        message: 'Turned off, inside {{ states.climate.family_room_nest.attributes.current_temperature }}C'
        data:
          sound: cosmic
#value_template: '{{ states.climate.family_room_nest.attributes.current_temperature }}'