###########################################
# Patio Light
###########################################
- alias: Patio Off After Arrival
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    - condition: state
      entity_id: switch.patio
      state: 'on'
  action:
    - delay: 00:02:00
    - service: switch.turn_off
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned off.
        data:
          sound: cosmic

- alias: Patio On After Departure
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.patio
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned on.
        data:
          sound: cosmic

###########################################
# Patio Camera
###########################################
# - alias: Homestreamer Camera Scrape
  # trigger:
    # platform: time
    # minutes: '/1'
    # seconds: 00
  # action:
    # - service: shell_command.scrape_patio_camera