###########################################
# Patio Light
###########################################
- alias: Patio On After Departure
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
        for:
            minutes: 10
      - condition: state
        entity_id: switch.patio
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned on.
        data:
          sound: cosmic
