###########################################
# Presence Based Rules
###########################################
- alias: Off While Home
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.netatmo_camera
    - service: switch.turn_off
      entity_id: switch.patio_camera

- alias: On While Home
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
        for:
            minutes: 10
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        before: '22:00'
  action:
    - service: switch.turn_on
      entity_id: switch.wemo_insight
    - service: switch.turn_on
      entity_id: switch.front_door

- alias: Off While Away
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: group.lights

- alias: On While Away
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: switch.turn_on
      entity_id: switch.netatmo_camera
    - service: switch.turn_on
      entity_id: switch.patio_camera
