###########################################
# Presence Based Rules
###########################################
- alias: Off While Home
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  action:
    - service: switch.turn_off
      entity_id: switch.netatmo_camera

- alias: On While Home
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    - condition: time
      before: '22:00'
  action:
    - service: switch.turn_on
      entity_id: switch.wemo_insight

- alias: Off While Away
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: group.lights

- alias: On While Away
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: switch.turn_on
      entity_id: switch.netatmo_camera