###########################################
# Presence Based Rules
###########################################
- alias: "Presence - Arrival - Turn On"
  trigger:
    platform: state
    entity_id: group.family_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
        for:
            minutes: 10
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        before: '22:00'
  action:
    - service: light.turn_on
      entity_id: light.kitchen
    - service: switch.turn_on
      entity_id: switch.front_door
