###########################################
# Roomba
###########################################
- alias: Roomba Schedule
  trigger:
    platform: time
    at: '08:30:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: device_tracker.bobbisiphone
        state: not_home
      - condition: state
        entity_id: group.family_devices
        state: not_home
  action:
    - service: switch.turn_on
      entity_id: switch.roomba
    - service: notify.pushover
      data:
        title: Roomba
        message: 'Cleaning started.'
        data:
          sound: cosmic
