###########################################
# Sunset & Sunrise
###########################################
- alias: Sunset Away Lights
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned on before sunset.
        data:
          sound: cosmic

- alias: Sunrise Away Lights
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:30:00"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
      - condition: state
        entity_id: switch.patio
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.patio
    - service: notify.pushover
      data:
        title: Patio Light
        message: Turned off after sunrise.
        data:
          sound: cosmic