esphome:
  name: office_lamp   # Name of the Node.
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: esp_office_lamp
    password: !secret wifi_password

captive_portal:

logger:

api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: office_lamp_wifi_signal
    update_interval: 60s
  - platform: uptime
    name: office_lamp_uptime

text_sensor:
  - platform: version
    name: office_lamp_esphome_version
  - platform: wifi_info
    ip_address:
      name: office_lamp_ip
    ssid:
      name: office_lamp_ssid
    bssid:
      name: office_lamp_bssid

switch:
  # Switch to restart the board
  - platform: restart
    name: office_lamp_restart

light:
  - platform: rgb
    name: "Office Lamp"    # Put the name that you want to see in Home Assistant.
    red: red_channel
    green: green_channel
    blue: blue_channel
    effects:             # Add few effects : Slow and fast random colors and an "in alarm" mode.
      - random:
          name: "Slow Random"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random"
          transition_length: 4s
          update_interval: 5s
      - strobe:
          name: Alarm
          colors:
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 0%
              blue: 100%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 0%
              blue: 100%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
      - strobe:
          name: Christmas
          colors:
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 30s
            - state: True
              brightness: 100%
              red: 0%
              blue: 0%
              green: 100%
              duration: 30s
            - state: True
              brightness: 100%
              red: 0%
              blue: 100%
              green: 0%
              duration: 30s
      - strobe:
          name: Halloween
          colors:
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 64.7%
              duration: 60s
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms
            - state: True
              brightness: 100%
              red: 100%
              blue: 0%
              green: 0%
              duration: 150ms
            - state: False
              duration: 100ms

output:
  - platform: esp8266_pwm
    id: red_channel
    pin: GPIO5
  - platform: esp8266_pwm
    id: green_channel
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_channel
    pin: GPIO13