Presence_Automation:
  name: "Presence Automation"
  entities:
    - automation.presence__arrival
    - automation.presence__departure

Roomba_Automation:
  name: "Roomba Automation"
  entities:
    - automation.vacuum__schedule
    - automation.vacuum__stop