Presence_Automation:
  name: "Presence Automation"
  entities:
    - automation.presence__arrival__turn_off
    - automation.presence__arrival__turn_on
    - automation.presence__departure__turn_off
    - automation.presence__departure__turn_on