###########################################
# Security Tab
###########################################
Security:
  view: yes
  icon: mdi:security-home
  entities:
    - group.sensors
    - group.cameras
    - group.patio_camera_events
    - group.front_door_camera_events
