###########################################
# Automation Tab
###########################################
automation:
  view: yes
  icon: mdi:settings
  name: Automation
  entities:
    - group.roomba_automation