input_boolean:
  vacuum_upstairs_manual:
    name: "Roomba"

input_select:
  roomba_upstairs_carpetboost:
    name: Vacuum Upstairs Carpet Boost
    options:
    - "Automatic"
    - "Eco-Mode"
    - "High Performance"

  roomba_upstairs_cleaningpasses:
    name: Vacuum Upstairs Cleaning Passes
    options:
    - "Automatic"
    - "One Pass"
    - "Two Passes"

alert:
  vacuum_upstairs_bin_full:
    name: "Upstairs Roomba Bin is Full"
    entity_id: sensor.vacuum_upstairs_bin_state_template
    state: 'Full'
    repeat: 240
    can_acknowledge: True
    notifiers:
      - pushover

sensor:
  - platform: mqtt
    name: "Vacuum Upstairs Cycle"
    state_topic: "vacuum/upstairs/status/cycle"
    force_update: true

  - platform: mqtt
    name: "Vacuum Upstairs Phase"
    state_topic: "vacuum/upstairs/status/phase"
    force_update: true

  - platform: mqtt
    name: "Vacuum Upstairs Initiator"
    state_topic: "vacuum/upstairs/status/initiator"
    force_update: true

  - platform: mqtt
    name: "Vacuum Upstairs BinPresent"
    state_topic: "vacuum/upstairs/status/binpresent"
    force_update: true

  - platform: mqtt
    name: "Vacuum Upstairs BinFull"
    state_topic: "vacuum/upstairs/status/binfull"
    force_update: true

  - platform: mqtt
    name: "Vacuum Upstairs BatPct"
    state_topic: "vacuum/upstairs/status/batpct"
    force_update: true
    unit_of_measurement: '%'
    device_class: battery

  - platform: template
    sensors:
      vacuum_upstairs_cycle_template:
        friendly_name: 'Cycle'
        value_template: >-
          {%- if is_state('sensor.vacuum_upstairs_phase', 'charge') %}
              Docked
          {%- elif is_state('sensor.vacuum_upstairs_phase', 'hmUsrDock') %}
              Docking
          {%- elif is_state('sensor.vacuum_upstairs_cycle', 'clean') %}
              Cleaning
          {%- else %}
              Offline
          {%- endif %}
    
  - platform: template
    sensors:
      vacuum_upstairs_bin_state_template:
        friendly_name: 'Bin State'
        value_template: >-
          {%- if is_state('sensor.vacuum_upstairs_binfull', 'true') %}
              Full
          {%- elif is_state('sensor.vacuum_upstairs_binfull', 'false') %}
              Empty
          {%- else %}
              Offline
          {%- endif %}

  - platform: template
    sensors:
      vacuum_upstairs_bin_presence_template:
        friendly_name: 'Bin Status'
        value_template: >-
          {%- if "sensor.vacuum_upstairs_binpresent", "true" %}
              Attached
          {%- elif "sensor.vacuum_upstairs_binpresent", "false" %}
              Ejected
          {%- else %}
              Offline
          {%- endif %}

  - platform: history_stats
    name: Vacuum Upstairs Runtime
    entity_id: sensor.vacuum_upstairs_cycle
    state: 'clean'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'